/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.aldorsolutions.dashboard.struts.action.users;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.aldorsolutions.dashboard.struts.form.users.UserEditForm;
import com.aldorsolutions.webfdms.admin.user.dao.UserDAO;
import com.aldorsolutions.webfdms.admin.user.model.UserDTO;
import com.aldorsolutions.webfdms.beans.DbUserSession;
import com.aldorsolutions.webfdms.util.FormatCurrency;
import com.aldorsolutions.webfdms.util.SessionValueKeys;

/**
 * MyEclipse Struts Creation date: 04-30-2007
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/userEdit" name="userEditForm"
 *                input="/user/userEdit.jsp" scope="request"
 *                validate="true"
 */
public class UserSaveAction extends Action {
	Logger logger = Logger.getLogger(UserSaveAction.class);
	
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		UserEditForm editForm = (UserEditForm) form;
		ActionMessages errors = new ActionMessages();
		
        HttpSession session =  request.getSession();
        DbUserSession user = (DbUserSession) session.getAttribute(SessionValueKeys.DB_USER);
        
        try {
        	if ( "Submit".equals(editForm.getSubmitButton()) ) {
        		saveUserForm(editForm, user, errors);
        	}
        } catch ( Exception e ) {
        	errors.add(ActionMessages.GLOBAL_MESSAGE, new ActionMessage("error.exception", e.getMessage()) );
			saveMessages(request, errors);
			e.printStackTrace();
			return (mapping.getInputForward());
        }
        
        session.setAttribute("userEditForm", null);
        
		return (mapping.findForward("userList"));
	}
	
	private void saveUserForm (UserEditForm form, DbUserSession user, ActionMessages errors) throws Exception {
		
        UserDTO userDTO = null;
        UserDAO dao = new UserDAO();
        userDTO = dao.getUser(form.getUserID());

        userDTO.setCompanyID((int) form.getCompanyID());
        userDTO.setEmail(form.getEmail());
        userDTO.setFirstName(form.getFirstName());
        userDTO.setLastName(form.getLastName());
        userDTO.setInitials(form.getInitials());
        userDTO.setName(form.getUserName());
        userDTO.setUserLimitOverride(form.isUserLimitOverride());
        
        if ( form.isUserLimitOverride() ) {
        	userDTO.setLimitExternalVendor( FormatCurrency.convertToCurrencyDbl(form.getExternalVendorLimit()) );
        	userDTO.setLimitInternalVendor( FormatCurrency.convertToCurrencyDbl(form.getInternalVendorLimit()) );
        } else {
        	userDTO.setLimitExternalVendor(0.0);
        	userDTO.setLimitInternalVendor(0.0);
        }
        
        if ( form.isVacationFlag() ) {
        	userDTO.setAccountingVacationFlag(true);
        	userDTO.setAccountingVacationUserID(form.getVacationUserID());
        } else {
        	userDTO.setAccountingVacationFlag(false);
        	userDTO.setAccountingVacationUserID(0);
        }
        
        dao.updateUser(userDTO);
		
	}
}