package com.aldorsolutions.webfdms.beans;

public interface DbVitalsDeceasedI extends com.aldorsolutions.webfdms.database.PersistentI
{
	public String getDateOfBirth();
	public String getDateOfBurial();
	public String getDateOfDeath();
	public String getDecFName();
	public String getDecFullName();
	public String getDecLName();
	public String getDecMaiden();
	public String getDecMarried();
	public String getDecMName();
	public String getDecmrmrs();
	public String getDecResCityTWP();
	public String getDecResCityTWPBox();
	public String getDecResCounty();
	public String getDecResInsideCity();
	public String getDecResLengthOfTime();
	public String getDecResMailCity();
	public String getDecResState();
	public String getDecResStreet();
	public String getDecResZip();
	public String getDecResPhone();
	public String getSalutation();
	public String getSex();
	public String getSSNo();
	public String getTimeOfDeath();
	public String getCountyOfBirth();
	public void setDateOfBirth(String lcl_arg0);
	public void setDateOfBurial(String lcl_arg0);
	public void setDateOfDeath(String lcl_arg0);
	public void setDecFName(String lcl_arg0);
	public void setDecFullName(String lcl_arg0);
	public void setDecLName(String lcl_arg0);
	public void setDecMaiden(String lcl_arg0);
	public void setDecMarried(String lcl_arg0);
	public void setDecMName(String lcl_arg0);
	public void setDecmrmrs(String lcl_arg0);
	public void setDecResCityTWP(String lcl_arg0);
	public void setDecResCityTWPBox(String lcl_arg0);
	public void setDecResCounty(String lcl_arg0);
	public void setDecResInsideCity(String lcl_arg0);
	public void setDecResLengthOfTime(String lcl_arg0);
	public void setDecResMailCity(String lcl_arg0);
	public void setDecResState(String lcl_arg0);
	public void setDecResStreet(String lcl_arg0);
	public void setDecResZip(String lcl_arg0);
	public void setDecResPhone(String lcl_arg0);
	public void setSalutation(String lcl_arg0);
	public void setSex(String lcl_arg0);
	public void setSSNo(String lcl_arg0);
	public void setTimeOfDeath(String lcl_arg0);
	public void setCountyOfBirth(String lcl_arg0);
}
