/*
 * Generated by XDoclet - Do not edit!
 */
package com.aldorsolutions.webfdms.company.ejb;

import javax.ejb.EJBException;

/**
 * Remote interface for NewCompanySetUp.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface NewCompanySetUp
   extends javax.ejb.EJBObject
{
   /**
    * AddsNew Company
    * @throws EJBException Thrown if method fails due to system-level error.    */
   public boolean addCompany( com.aldorsolutions.webfdms.company.model.CompanyDTO company )
      throws java.rmi.RemoteException;

}
