package com.callfire.SMSService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SMSServicePortType", targetNamespace = "http://api.campaign.dialer.skyyconsulting.com")
public interface SMSServicePortType {

	/**
	 * 
	 * @param campaignName
	 * @param numbers
	 * @param key
	 * @return returns long
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://api.campaign.dialer.skyyconsulting.com")
	@RequestWrapper(localName = "sendSMSCampaign", targetNamespace = "http://api.campaign.dialer.skyyconsulting.com", className = "com.callfire.SMSService.SendSMSCampaign")
	@ResponseWrapper(localName = "sendSMSCampaignResponse", targetNamespace = "http://api.campaign.dialer.skyyconsulting.com", className = "com.callfire.SMSService.SendSMSCampaignResponse")
	public long sendSMSCampaign(
			@WebParam(name = "key", targetNamespace = "http://api.campaign.dialer.skyyconsulting.com") String key,
			@WebParam(name = "numbers", targetNamespace = "http://api.campaign.dialer.skyyconsulting.com") ArrayOfString numbers,
			@WebParam(name = "campaignName", targetNamespace = "http://api.campaign.dialer.skyyconsulting.com") String campaignName);

}
