/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 * CJongs
 */
package com.aldorsolutions.dashboard.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-17-2007
 * 
 * XDoclet definition:
 * @struts.form name="mainForm"
 */
public class MainForm extends ActionForm {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7570959813472847388L;

	/** userID property */
	private String userID;

	/** roles property */
	private String roles;

	
	private String userLocaleId; 
	
	private String userLocationId;
	
	private String requestType;
	
	private boolean specificLoc;
	
	private String SpecificLocOpt;
	/*
	 * Generated Methods
	 */



	public String getUserLocationId() {
		return userLocationId;
	}

	public void setUserLocationId(String userLocationId) {
		this.userLocationId = userLocationId;
	}

	public String getUserLocaleId() {
		return userLocaleId;
	}

	public void setUserLocaleId(String userLocaleId) {
		this.userLocaleId = userLocaleId;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the userID.
	 * @return String
	 */
	public String getUserID() {
		return userID;
	}

	/** 
	 * Set the userID.
	 * @param userID The userID to set
	 */
	public void setUserID(String userID) {
		this.userID = userID;
	}

	/** 
	 * Returns the roles.
	 * @return String
	 */
	public String getRoles() {
		return roles;
	}

	/** 
	 * Set the roles.
	 * @param roles The roles to set
	 */
	public void setRoles(String roles) {
		this.roles = roles;
	}

	public String getRequestType() {
		return requestType;
	}

	public void setRequestType(String requestType) {
		this.requestType = requestType;
	}

	public boolean isSpecificLoc() {
		return specificLoc;
	}

	public void setSpecificLoc(boolean specificLoc) {
		this.specificLoc = specificLoc;
	}

	public String getSpecificLocOpt() {
		return SpecificLocOpt;
	}

	public void setSpecificLocOpt(String specificLocOpt) {
		SpecificLocOpt = specificLocOpt;
	}

}