--
-- Current Database: demo
--

CREATE DATABASE /*!32312 IF NOT EXISTS*/ demo;

USE demo;

--
-- Table structure for table `apaccounts`
--

CREATE TABLE apaccounts (
  AccountID int(11) NOT NULL auto_increment,
  AccountNumber varchar(15) NOT NULL default '',
  Description varchar(30) NOT NULL default '',
  LocaleID int(11) NOT NULL default '0',
  LocationID int(11) NOT NULL default '0',
  PRIMARY KEY  (AccountID)
) TYPE=InnoDB;

--
-- Table structure for table `apdistribution`
--

CREATE TABLE apdistribution (
  RecordID int(11) NOT NULL auto_increment,
  MasterID int(11) NOT NULL default '0',
  DistributionAcctID int(11) NOT NULL default '0',
  DistributionAmount int(11) NOT NULL default '0',
  TranType char(1) NOT NULL default '',
  Posted char(1) default NULL,
  Memo varchar(30) default NULL,
  PRIMARY KEY  (RecordID),
  KEY Master_index (MasterID)
) TYPE=InnoDB;

--
-- Table structure for table `apmaster`
--

CREATE TABLE apmaster (
  MasterID int(11) NOT NULL auto_increment,
  VendorID int(11) NOT NULL default '0',
  LocationID int(11) NOT NULL default '0',
  LocaleID int(11) NOT NULL default '0',
  UserID int(11) NOT NULL default '0',
  InvoiceNumber varchar(20) default NULL,
  InvoiceDate date default NULL,
  DueDate date default NULL,
  Memo varchar(80) default NULL,
  Handwritten char(1) default NULL,
  CheckToBePrinted char(1) default NULL,
  DiscountAmount int(11) default NULL,
  CheckNumber int(11) default NULL,
  Balance int(11) default NULL,
  CheckDate date default NULL,
  InvoiceTotal int(11) default NULL,
  VoidedCode char(1) default '',
  PRIMARY KEY  (MasterID)
) TYPE=InnoDB;

--
-- Table structure for table `apvendors`
--

CREATE TABLE apvendors (
  VendorID int(11) NOT NULL auto_increment,
  Locale int(11) NOT NULL default '0',
  Name varchar(30) NOT NULL default '',
  Addr1 varchar(30) default NULL,
  Addr2 varchar(30) default NULL,
  CityState varchar(30) default NULL,
  PostalCode varchar(15) default NULL,
  ContactName varchar(30) default NULL,
  Phone varchar(20) default NULL,
  EmailAddr varchar(40) default NULL,
  DefaultAcct int(11) default NULL,
  Notes varchar(253) default NULL,
  LocationID int(11) default '0',
  DeleteCode char(1) default NULL,
  PRIMARY KEY  (VendorID)
) TYPE=InnoDB;

--
-- Table structure for table `arrangers`
--

CREATE TABLE arrangers (
  Identity int(11) NOT NULL auto_increment,
  Name varchar(30) NOT NULL default '',
  LicenseNumber varchar(15) default NULL,
  ArrangerNumber smallint(6) default NULL,
  SocSecNo varchar(15) default NULL,
  Locale int(11) NOT NULL default '0',
  DeleteCode char(1) default NULL,
  PRIMARY KEY  (Identity)
) TYPE=InnoDB;

--
-- Table structure for table `billtoparties`
--

CREATE TABLE billtoparties (
  RecordNumber int(11) NOT NULL auto_increment,
  VitalsID int(11) NOT NULL default '0',
  Honorific varchar(10) default NULL,
  FirstName varchar(25) default NULL,
  LastName varchar(25) default NULL,
  StreetAddr1 varchar(30) default NULL,
  StreetAddr2 varchar(30) default NULL,
  City varchar(25) default NULL,
  State varchar(20) default NULL,
  Zip varchar(10) default NULL,
  HomePhone varchar(20) default NULL,
  SocialSecNo varchar(10) default NULL,
  Relation varchar(20) default NULL,
  ContractSignerYN char(1) default NULL,
  ModifiedFlag char(1) default NULL,
  Language varchar(15) default NULL,
  CashSale char(1) default NULL,
  Refused char(1) default NULL,
  SendInvoice char(1) default NULL,
  SequenceNumber smallint(6) default NULL,
  DeleteCode char(1) NOT NULL default '',
  WorkPhone varchar(20) default NULL,
  FileVersion smallint(6) default NULL,
  County varchar(30) default NULL,
  Street3 varchar(30) default NULL,
  Street4 varchar(30) default NULL,
  DateModified date default NULL,
  TimeModified time default NULL,
  EmailAddress varchar(50) default NULL,
  PRIMARY KEY  (RecordNumber),
  KEY VitalsMasterKey (VitalsID)
) TYPE=InnoDB;

--
-- Table structure for table `charges`
--

CREATE TABLE charges (
  VitalsMasterKey int(11) default NULL,
  ChargeType smallint(6) default NULL,
  Description varchar(50) default NULL,
  Amount int(11) default NULL,
  ARacct varchar(10) default NULL,
  GLacct varchar(10) default NULL,
  TaxExemptAmt int(11) default NULL,
  TaxCode varchar(10) default NULL,
  DateModified date default NULL,
  TimeModified time default NULL,
  Sequence smallint(6) default NULL,
  SPFcode char(1) NOT NULL default '',
  InventoryItemName varchar(15) default NULL,
  InvMasterKey int(11) default NULL,
  CategoryCode char(1) default NULL,
  OriginalPrice int(11) default NULL,
  RecordVersion smallint(6) default NULL,
  AutoIndex int(11) NOT NULL auto_increment,
  PriceListId int(11) default NULL,
  InvOnHandID int(11) NOT NULL default '0',
  PRIMARY KEY  (AutoIndex),
  KEY VitalsKey (VitalsMasterKey)
) TYPE=InnoDB;

--
-- Table structure for table `depositsummary`
--

CREATE TABLE depositsummary (
  autoKey int(11) NOT NULL auto_increment,
  BatchNumber varchar(9) NOT NULL default '',
  FromDate varchar(8) default NULL,
  FromTime varchar(6) default NULL,
  ToDate varchar(8) default NULL,
  ToTime varchar(6) default NULL,
  TotalCash int(11) default NULL,
  TotalChecks int(11) default NULL,
  TotalOther int(11) default NULL,
  TotalAll int(11) default NULL,
  DateModified timestamp(14) NOT NULL,
  FileVersion smallint(6) default NULL,
  PRIMARY KEY  (autoKey)
) TYPE=InnoDB;

--
-- Table structure for table `donations`
--

CREATE TABLE donations (
  SequenceNumber int(11) NOT NULL auto_increment,
  VitalsID int(11) default NULL,
  Honorific varchar(10) default NULL,
  FirstName varchar(25) default NULL,
  LastName varchar(25) default NULL,
  Address1 varchar(25) default NULL,
  Address2 varchar(25) default NULL,
  City varchar(25) default NULL,
  State varchar(20) default NULL,
  PostalCode varchar(10) default NULL,
  CharityName varchar(30) default NULL,
  DonationAmount int(11) default NULL,
  PaymentType varchar(15) default NULL,
  FileVersion smallint(6) default NULL,
  HistTranNo int(11) default NULL,
  DateModified date default NULL,
  TimeModified time default NULL,
  Street3 varchar(25) default NULL,
  Street4 varchar(25) default NULL,
  PRIMARY KEY  (SequenceNumber),
  KEY VitalsMasterKey (VitalsID)
) TYPE=InnoDB;

--
-- Table structure for table `embalmingreport`
--

CREATE TABLE embalmingreport (
  VitalsID int(11) NOT NULL default '0',
  DateEmbalmed varchar(8) default NULL,
  TimeStarted varchar(10) default NULL,
  TimeEnded varchar(10) default NULL,
  TimeReceived varchar(10) default NULL,
  OperationYN char(1) default NULL,
  OperationType varchar(60) default NULL,
  AutopsyYN char(1) default NULL,
  AutopsyComplete char(1) default NULL,
  AutopsyTrunk char(1) default NULL,
  AutopsyCranial char(1) default NULL,
  AutopsyBeforeEmb char(1) default NULL,
  AutopsyAfter char(1) default NULL,
  TimeBetweenDthAutops varchar(30) default NULL,
  TimeReleased varchar(15) default NULL,
  RefrigerationYN char(1) default NULL,
  RefrigDuration varchar(30) default NULL,
  FrozenBox char(1) default NULL,
  ThawedBox char(1) default NULL,
  RigorSlight char(1) default NULL,
  RigorModerate char(1) default NULL,
  RigorIntense char(1) default NULL,
  BodyWarm char(1) default NULL,
  BodyCold char(1) default NULL,
  AbdominalSlight char(1) default NULL,
  AbdominalModerate char(1) default NULL,
  AbdominalIntense char(1) default NULL,
  AbdominalLiquid char(1) default NULL,
  AbdominalGas char(1) default NULL,
  PurgeYN char(1) default NULL,
  PurgeDescription varchar(20) default NULL,
  PurgeAfterYN char(1) default NULL,
  PurgeAfterDescr varchar(20) default NULL,
  DropsicalAbdomen char(1) default NULL,
  DropsicalThorax char(1) default NULL,
  DropsicalRleg char(1) default NULL,
  DropsicalLleg char(1) default NULL,
  DropsicalRarm char(1) default NULL,
  DropsicalLarm char(1) default NULL,
  DropsicalFace char(1) default NULL,
  JaundiceNone char(1) default NULL,
  JaundiceModerate char(1) default NULL,
  JaundiceAcute char(1) default NULL,
  GangreneNone char(1) default NULL,
  GangreneModerate char(1) default NULL,
  GangreneAcute char(1) default NULL,
  Wounds varchar(80) default NULL,
  BloodDiscolor varchar(80) default NULL,
  OtherDiscolor varchar(80) default NULL,
  Comments varchar(80) default NULL,
  TimeBetweenDeathEmb varchar(30) default NULL,
  Weather varchar(30) default NULL,
  Axillary char(1) default NULL,
  Carotid char(1) default NULL,
  Brachial char(1) default NULL,
  Iliac char(1) default NULL,
  FemoralArtery char(1) default NULL,
  AxillaryVein char(1) default NULL,
  Jugular char(1) default NULL,
  Basilic char(1) default NULL,
  IliacVein char(1) default NULL,
  FemoralVein char(1) default NULL,
  OtherArtery varchar(30) default NULL,
  OtherVein varchar(30) default NULL,
  InjectionDilution char(1) default NULL,
  InjectionHalfGal char(1) default NULL,
  InjectionPulsePressu char(1) default NULL,
  InjectionMotor char(1) default NULL,
  InjectionGravity char(1) default NULL,
  InjectionHandPump char(1) default NULL,
  InjectionBulbSyring char(1) default NULL,
  PreInjection varchar(30) default NULL,
  PreInj1 varchar(15) default NULL,
  PreInj2 varchar(15) default NULL,
  PreInj3 varchar(15) default NULL,
  PreInj4 varchar(15) default NULL,
  PreInj5 varchar(15) default NULL,
  ArterialFluid varchar(30) default NULL,
  ArtFluid1 varchar(15) default NULL,
  ArtFluid2 varchar(15) default NULL,
  ArtFluid3 varchar(15) default NULL,
  ArtFluid4 varchar(15) default NULL,
  ArtFluid5 varchar(15) default NULL,
  FluidModifier varchar(30) default NULL,
  FluidMod1 varchar(15) default NULL,
  FluidMod2 varchar(15) default NULL,
  FluidMod3 varchar(15) default NULL,
  FluidMod4 varchar(15) default NULL,
  FluidMod5 varchar(15) default NULL,
  Conditioner varchar(30) default NULL,
  Cond1 varchar(15) default NULL,
  Cond2 varchar(15) default NULL,
  Cond3 varchar(15) default NULL,
  Cond4 varchar(15) default NULL,
  Cond5 varchar(15) default NULL,
  CavityFluid varchar(30) default NULL,
  CavityQtyUsed varchar(15) default NULL,
  CavityMethod varchar(15) default NULL,
  QtyDrainage varchar(50) default NULL,
  HeavyClots char(1) default NULL,
  MediumClots char(1) default NULL,
  LightClots char(1) default NULL,
  Exceptions varchar(80) default NULL,
  AdditionalTreatment varchar(80) default NULL,
  PostEmbalmingRecheck varchar(200) default NULL,
  ConditionEnding varchar(15) default NULL,
  Condition2ndDay varchar(15) default NULL,
  ConditionAtService varchar(15) default NULL,
  OtherTreatment varchar(80) default NULL,
  AdditionalRemarks varchar(80) default NULL,
  EmbalmerLicense varchar(30) default NULL,
  AssistedBy varchar(30) default NULL,
  DateModified date default NULL,
  TimeModified time default NULL,
  MouthNeedle char(1) default NULL,
  MouthSuture char(1) default NULL,
  MouthOther char(1) default NULL,
  TeethPresent char(1) default NULL,
  Dentures char(1) default NULL,
  ArtificialReplacemen char(1) default NULL,
  EyesCaps char(1) default NULL,
  EyesSuture char(1) default NULL,
  EyesOther char(1) default NULL,
  PrepRoomCleaned char(1) default NULL,
  PRIMARY KEY  (VitalsID)
) TYPE=InnoDB;

--
-- Table structure for table `fdmscust`
--

CREATE TABLE fdmscust (
  VitalsMasterKey int(11) NOT NULL default '0',
  Custom1 varchar(49) default NULL,
  Custom2 varchar(49) default NULL,
  Custom3 varchar(49) default NULL,
  Custom4 varchar(49) default NULL,
  Custom5 varchar(49) default NULL,
  Custom6 varchar(49) default NULL,
  Custom7 varchar(49) default NULL,
  Custom8 varchar(49) default NULL,
  Custom9 varchar(49) default NULL,
  Custom10 varchar(49) default NULL,
  Custom11 varchar(49) default NULL,
  Custom12 varchar(49) default NULL,
  Custom13 varchar(49) default NULL,
  Custom14 varchar(49) default NULL,
  Custom15 varchar(49) default NULL,
  Custom16 varchar(49) default NULL,
  Custom17 varchar(49) default NULL,
  Custom18 varchar(49) default NULL,
  Custom19 varchar(49) default NULL,
  Custom20 varchar(49) default NULL,
  Custom21 varchar(49) default NULL,
  Custom22 varchar(49) default NULL,
  Custom23 varchar(49) default NULL,
  Custom24 varchar(49) default NULL,
  Custom25 varchar(49) default NULL,
  Custom26 varchar(49) default NULL,
  Custom27 varchar(49) default NULL,
  Custom28 varchar(49) default NULL,
  Custom29 varchar(49) default NULL,
  Custom30 varchar(49) default NULL,
  Custom31 varchar(49) default NULL,
  Custom32 varchar(49) default NULL,
  Custom33 varchar(49) default NULL,
  Custom34 varchar(49) default NULL,
  Custom35 varchar(49) default NULL,
  Custom36 varchar(49) default NULL,
  Custom37 varchar(49) default NULL,
  Custom38 varchar(49) default NULL,
  Custom39 varchar(49) default NULL,
  Custom40 varchar(49) default NULL,
  Long1 varchar(79) default NULL,
  Long2 varchar(79) default NULL,
  Long3 varchar(79) default NULL,
  Long4 varchar(79) default NULL,
  Long5 varchar(79) default NULL,
  Long6 varchar(79) default NULL,
  Long7 varchar(79) default NULL,
  Long8 varchar(79) default NULL,
  Long9 varchar(79) default NULL,
  Long10 varchar(79) default NULL,
  Long11 varchar(79) default NULL,
  Long12 varchar(79) default NULL,
  Long13 varchar(79) default NULL,
  Long14 varchar(79) default NULL,
  Long15 varchar(79) default NULL,
  Long16 varchar(79) default NULL,
  Long17 varchar(79) default NULL,
  Long18 varchar(79) default NULL,
  Long19 varchar(79) default NULL,
  Long20 varchar(79) default NULL,
  Long21 varchar(79) default NULL,
  Long22 varchar(79) default NULL,
  Long23 varchar(79) default NULL,
  Long24 varchar(79) default NULL,
  Long25 varchar(79) default NULL,
  Long26 varchar(79) default NULL,
  Long27 varchar(79) default NULL,
  Long28 varchar(79) default NULL,
  Long29 varchar(79) default NULL,
  Long30 varchar(79) default NULL,
  Long31 varchar(79) default NULL,
  Long32 varchar(79) default NULL,
  Long33 varchar(79) default NULL,
  Long34 varchar(79) default NULL,
  Long35 varchar(79) default NULL,
  Long36 varchar(79) default NULL,
  Long37 varchar(79) default NULL,
  Long38 varchar(79) default NULL,
  Long39 varchar(79) default NULL,
  Long40 varchar(79) default NULL,
  DateModified date default NULL,
  TimeModified time default NULL,
  PRIMARY KEY  (VitalsMasterKey)
) TYPE=InnoDB;

--
-- Table structure for table `financialdata`
--

CREATE TABLE financialdata (
  VitalsMasterKey int(11) NOT NULL default '0',
  SaleType varchar(25) default NULL,
  CalcFinanceChrgYN smallint(6) default NULL,
  FinanceChargeRate double default NULL,
  SaleDate varchar(8) default NULL,
  DueDate varchar(8) default NULL,
  DateInvoiceSent varchar(8) default NULL,
  AmountFinanced int(11) default NULL,
  InterestTotal int(11) default NULL,
  Term smallint(6) default NULL,
  MonthlyPaymentAmt int(11) default NULL,
  LastFinancedPmt int(11) default NULL,
  FirstPaymentDueDate varchar(8) default NULL,
  TotalPaidToDate int(11) default NULL,
  FirstFinChargCalc char(1) default NULL,
  FinChargeSchedule varchar(8) default NULL,
  FinChargeLastCalc varchar(8) default NULL,
  EagleApplNo varchar(6) default NULL,
  EagleAuthCode varchar(5) default NULL,
  LastPaymentRespons varchar(29) default NULL,
  LastPaymentMemo varchar(29) default NULL,
  LastPaymentAmount int(11) default NULL,
  LastPaymentDate varchar(8) default NULL,
  SentToAccounting smallint(6) default NULL,
  TotalCharges int(11) default NULL,
  LastFinanceCharge int(11) default NULL,
  LastReceiptNo int(11) default NULL,
  FileVersion smallint(6) default NULL,
  MiscNotes text,
  PriceListTable varchar(14) default NULL,
  PackageTable varchar(14) default NULL,
  FamilyUsedUsBefore char(1) default NULL,
  FnrlHomePrevUsed varchar(25) default NULL,
  AdvSource varchar(25) default NULL,
  DateModified date default NULL,
  TimeModified time default NULL,
  PRIMARY KEY  (VitalsMasterKey)
) TYPE=InnoDB;

--
-- Table structure for table `formsavailable`
--

CREATE TABLE formsavailable (
  FormId int(11) NOT NULL auto_increment,
  Locale int(11) NOT NULL default '0',
  Description varchar(30) NOT NULL default '',
  ReportName varchar(30) NOT NULL default '',
  Category int(11) NOT NULL default '0',
  SelectionFormula varchar(253) default NULL,
  exportType varchar(10) NOT NULL default 'PDF',
  MarginLeft int(11) NOT NULL default '0',
  MarginRight int(11) NOT NULL default '0',
  MarginTop int(11) NOT NULL default '0',
  MarginBottom int(11) NOT NULL default '0',
  ChainToReport int(11) default '0',
  UserDefined tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (FormId)
) TYPE=InnoDB;

--
-- Table structure for table `formsprinted`
--

CREATE TABLE formsprinted (
  PrintedId int(11) NOT NULL auto_increment,
  CaseId int(11) NOT NULL default '0',
  FormId int(11) NOT NULL default '0',
  CompletedYN char(1) NOT NULL default '',
  CompletedDate date NOT NULL default '0000-00-00',
  CompletedTime time NOT NULL default '00:00:00',
  PRIMARY KEY  (PrintedId),
  KEY VitalsMasterKey (CaseId)
) TYPE=InnoDB;

--
-- Table structure for table `glacctdefault`
--

CREATE TABLE glacctdefault (
  glacctID int(11) NOT NULL auto_increment,
  locale int(11) default NULL,
  deleteCode char(1) default NULL,
  location int(11) default NULL,
  category varchar(30) default NULL,
  disposition varchar(30) default NULL,
  saleType varchar(50) default NULL,
  revenueAcct varchar(15) default NULL,
  invAssetAcct varchar(15) default NULL,
  InvCogsAcct varchar(15) default NULL,
  PRIMARY KEY  (glacctID),
  KEY glacctID (glacctID)
) TYPE=MyISAM;

--
-- Table structure for table `invchapelindex`
--

CREATE TABLE invchapelindex (
  ItemNumber int(11) NOT NULL default '0',
  LocationNumber int(11) NOT NULL default '0',
  IndexID int(11) NOT NULL auto_increment,
  PRIMARY KEY  (IndexID),
  KEY ItemNumber (ItemNumber),
  KEY LocationNumber (LocationNumber)
) TYPE=InnoDB;

--
-- Table structure for table `invhistory`
--

CREATE TABLE invhistory (
  ItemName varchar(14) NOT NULL default '',
  ItemSequenceNo int(11) default NULL,
  SerialNumber varchar(25) default NULL,
  TransactionType char(1) NOT NULL default '',
  TransactionDate varchar(8) NOT NULL default '',
  ReferenceNumber varchar(9) default NULL,
  VitalsMasterKey int(11) default NULL,
  Location varchar(24) default NULL,
  Quantity int(11) default NULL,
  SellingPrice int(11) default NULL,
  WholesaleCost int(11) default NULL,
  SalesAcct varchar(9) default NULL,
  AssetAcct varchar(9) default NULL,
  CostAcct varchar(9) default NULL,
  Description varchar(29) default NULL,
  UserInitials char(3) default NULL,
  DateModified date default NULL,
  TimeModified time default NULL,
  MasterID int(11) default NULL,
  Identity int(11) NOT NULL auto_increment,
  PRIMARY KEY  (Identity)
) TYPE=InnoDB;

--
-- Table structure for table `invmaster`
--

CREATE TABLE invmaster (
  ItemName varchar(14) NOT NULL default '',
  Description varchar(79) NOT NULL default '',
  StockType char(1) NOT NULL default '',
  ProductLine varchar(30) NOT NULL default '',
  Showroom char(1) default NULL,
  Supplier varchar(29) default NULL,
  Cost int(11) default NULL,
  Price int(11) default NULL,
  MinimumOnHand smallint(6) default NULL,
  ReorderQuantity int(11) default NULL,
  SalesGLAcct varchar(9) default NULL,
  AssetGLAcct varchar(9) default NULL,
  CostGLAcct varchar(9) default NULL,
  TaxExempt double default NULL,
  TaxCode varchar(4) default NULL,
  RecordVersion smallint(6) default NULL,
  DeleteCode char(1) default NULL,
  CasketTypeCode char(1) default NULL,
  CasketUseCategory char(1) default NULL,
  InteriorDescription varchar(50) default NULL,
  ExteriorDescription varchar(50) default NULL,
  ExteriorCode varchar(4) default NULL,
  Notes varchar(254) default NULL,
  DateModified date default NULL,
  TimeModified time default NULL,
  Identity int(11) NOT NULL auto_increment,
  Locale int(11) default NULL,
  GLacctCategory char(1) default NULL,
  SequenceNo int(11) default NULL,
  ContractLineNo smallint(6) default NULL,
  ImageUrl varchar(250) default NULL,
  PRIMARY KEY  (Identity),
  UNIQUE KEY nameIndex (ItemName)
) TYPE=InnoDB;

--
-- Table structure for table `invonhand`
--

CREATE TABLE invonhand (
  ItemName varchar(14) default NULL,
  ItemSequenceNo int(11) default NULL,
  SerialNumber varchar(25) default NULL,
  ShowRoom char(1) default NULL,
  DateIn varchar(8) default NULL,
  InvoiceNumber varchar(10) default NULL,
  Location varchar(24) default NULL,
  Quantity int(11) default NULL,
  Cost int(11) default NULL,
  Notes varchar(99) default NULL,
  DateModified date default NULL,
  TimeModified time default NULL,
  Identity int(11) NOT NULL auto_increment,
  MasterID int(11) default NULL,
  PRIMARY KEY  (Identity),
  KEY MasterIdIndex (MasterID),
  KEY ItemNameIndex (ItemName)
) TYPE=InnoDB;

--
-- Table structure for table `locales`
--

CREATE TABLE locales (
  LocaleID int(11) NOT NULL auto_increment,
  Name varchar(40) NOT NULL default '',
  NextContractNo int(11) default '0',
  NextReceiptNo int(11) default '0',
  NextNonCashNo int(11) default '0',
  LastFinChgDate date default NULL,
  AccessExpirationDate date NOT NULL default '0000-00-00',
  NumberOfUsers int(10) NOT NULL default '0',
  NextPreNeedNumber int(11) default '0',
  InterfaceType int(11) default '0',
  ManagerName varchar(30) default NULL,
  AbbitID int(11) default NULL,
  DefaultBankID int(11) default NULL,
  DefaultCommission double default NULL,
  DefaultRefundRate double default NULL,
  DefaultInflationRate double default '0.04',
  PreneedLicense char(1) default NULL,
  AtneedLicense char(1) default NULL,
  DefaultSaleDateCode int(11) default '0',
  DaysBeforeDue int(11) default '30',
  PRIMARY KEY  (LocaleID)
) TYPE=InnoDB;

--
-- Table structure for table `locations`
--

CREATE TABLE locations (
  LocationID int(11) NOT NULL auto_increment,
  Name varchar(40) NOT NULL default '',
  Locale int(11) NOT NULL default '0',
  CompanyNumber varchar(10) default NULL,
  StandardServiceFee int(11) default NULL,
  PriceListVersion varchar(15) default NULL,
  PackageVersion varchar(15) default NULL,
  CashGlAcct varchar(10) default NULL,
  ArGlAcct varchar(10) default NULL,
  FinChrgGlAcct varchar(10) default NULL,
  InactiveCode char(1) default NULL,
  ApGlAcct varchar(10) default NULL,
  DiscountGlAcct varchar(10) default NULL,
  NextCheckNumber int(11) default NULL,
  DiscountHandlingCode char(1) default NULL,
  CheckingAcctBalance int(11) default NULL,
  ManagerName varchar(30) default NULL,
  Addr1 varchar(50) default NULL,
  Addr2 varchar(50) default NULL,
  Addr3 varchar(50) default NULL,
  City varchar(50) default NULL,
  State char(2) default NULL,
  ZipCode varchar(10) default NULL,
  County varchar(30) default NULL,
  PhoneNumber varchar(20) default NULL,
  OtherPhone varchar(20) default NULL,
  LicenseNumber varchar(10) default NULL,
  genericVitals char(1) default NULL,
  UndepositedFundsAcct varchar(10) default NULL,
  UseUndepositedFundsAcct tinyint(1) NOT NULL default '0',
  PRIMARY KEY  (LocationID)
) TYPE=InnoDB;

--
-- Table structure for table `memorial`
--

CREATE TABLE memorial (
  memorialID int(11) NOT NULL auto_increment,
  Locale int(11) NOT NULL default '0',
  description varchar(50) NOT NULL default '',
  verse text NOT NULL,
  PRIMARY KEY  (memorialID)
) TYPE=InnoDB;

--
-- Table structure for table `obituary`
--

CREATE TABLE obituary (
  VitalsId int(11) NOT NULL auto_increment,
  ObitNotice text NOT NULL,
  PRIMARY KEY  (VitalsId)
) TYPE=InnoDB;

--
-- Table structure for table `packagepricelist`
--

CREATE TABLE packagepricelist (
  PriceListVersion varchar(12) NOT NULL default '',
  PkgPriceListId int(11) default NULL,
  IncludedCode char(1) default NULL,
  Sequencenumber smallint(6) default NULL,
  PriceListId int(11) default NULL,
  Description varchar(39) default NULL,
  RecordId int(11) NOT NULL auto_increment,
  PRIMARY KEY  (RecordId),
  KEY versionIndex (PriceListVersion),
  KEY gplKeyIndex (PkgPriceListId)
) TYPE=InnoDB;

--
-- Table structure for table `pmntcomponents`
--

CREATE TABLE pmntcomponents (
  PmntComponentID int(11) NOT NULL auto_increment,
  VitalsID int(11) NOT NULL default '0',
  Code char(3) NOT NULL default '',
  Description varchar(30) NOT NULL default '',
  SaleAmount int(11) default NULL,
  PaidAmount int(11) default NULL,
  Type char(1) default NULL,
  DateModified date default NULL,
  TimeModified time default NULL,
  PRIMARY KEY  (PmntComponentID),
  KEY VitalsMasterKey (VitalsID)
) TYPE=InnoDB;

--
-- Table structure for table `pncharges`
--

CREATE TABLE pncharges (
  ContractID int(11) default NULL,
  ChargeType smallint(6) default NULL,
  Description varchar(50) default NULL,
  Amount int(11) default NULL,
  Sequence smallint(6) default NULL,
  SPFcode char(1) NOT NULL default '',
  PriceListId int(11) default NULL,
  InvMasterKey int(11) default NULL,
  CategoryCode char(1) default NULL,
  AutoIndex int(11) NOT NULL auto_increment,
  TaxCode varchar(15) default NULL,
  TaxExemptAmt int(11) default NULL,
  PRIMARY KEY  (AutoIndex),
  KEY ContractIndex (ContractID)
) TYPE=InnoDB;

--
-- Table structure for table `pncontracts`
--

CREATE TABLE pncontracts (
  ContractID int(11) NOT NULL auto_increment,
  VitalsMasterKey int(11) NOT NULL default '0',
  ContractNumber int(11) default NULL,
  ContractType int(11) default NULL,
  Installment char(1) default NULL,
  SendAnnualStmt char(1) default NULL,
  CertifiedIrrevocable char(1) default NULL,
  Taxpayer char(1) default NULL,
  Send1099To char(1) default NULL,
  BankID int(11) default NULL,
  ContractDate date default NULL,
  CommissionRate double default NULL,
  DiscountRate double default NULL,
  Refund double default NULL,
  PackageID int(11) default NULL,
  TotalCharges int(11) default NULL,
  DownPayment int(11) default NULL,
  ContractNumberOfPmts int(11) default NULL,
  DateFirstPmtDue date default NULL,
  InterestRate double default NULL,
  TotalFinanceCharge int(11) default NULL,
  MonthlyPmtAmount int(11) default NULL,
  NumberPmtsMade int(11) default NULL,
  TotalPaidToDate int(11) default NULL,
  LastPmtDate date default NULL,
  LastPmtAmount int(11) default NULL,
  LastPmtCommAmount int(11) default NULL,
  LastPmtMemo varchar(255) default NULL,
  LastPmtFundsForCode char(1) default NULL,
  LastPmtCommBox char(1) default NULL,
  FulfillmentContactName varchar(30) default NULL,
  FulfillmentContactPhone varchar(30) default NULL,
  CancellationDate date default NULL,
  CancellationType char(1) default NULL,
  CancellationAck char(1) default NULL,
  PartialWithdrawalAmount int(11) default NULL,
  CancellationFundsName varchar(30) default NULL,
  CancellationFundsAddr varchar(30) default NULL,
  CancellationFundsCity varchar(25) default NULL,
  CancellationFundsState varchar(20) default NULL,
  CancellationFundsZip varchar(10) default NULL,
  PriceListTable varchar(15) default NULL,
  Notes text,
  PRIMARY KEY  (ContractID),
  KEY VitalsKey (VitalsMasterKey)
) TYPE=InnoDB;

--
-- Table structure for table `pnpayments`
--

CREATE TABLE pnpayments (
  ContractID int(11) default NULL,
  RecordID int(11) NOT NULL auto_increment,
  PmtDate date default NULL,
  PmtAmount int(11) default NULL,
  PmtCommAmount int(11) default NULL,
  PmtMemo varchar(255) default NULL,
  PmtFundsForCode char(1) default NULL,
  PmtCommBox char(1) default NULL,
  PRIMARY KEY  (RecordID),
  KEY ContractIndex (ContractID)
) TYPE=InnoDB;

--
-- Table structure for table `pricelist`
--

CREATE TABLE pricelist (
  PriceListVersion varchar(12) NOT NULL default '',
  GPLKey varchar(8) NOT NULL default '',
  MasterDescription varchar(39) default NULL,
  ContractDescription varchar(39) default NULL,
  Price int(11) default NULL,
  ToPrice int(11) default NULL,
  ItemCategory char(1) default NULL,
  GPLDescription varchar(150) default NULL,
  Active char(1) default NULL,
  GridRowNumber smallint(6) default NULL,
  GPLPriceExtension varchar(15) default NULL,
  ContractLineNumber smallint(6) default NULL,
  GPLRegulated char(1) default NULL,
  GPLPrintCode char(1) default NULL,
  TaxCode varchar(5) default NULL,
  TaxExemptAmount int(11) default NULL,
  GLAcctNo varchar(10) default NULL,
  PackageItem char(1) default NULL,
  PriceListID int(11) NOT NULL auto_increment,
  InvoiceSeqNo int(11) default NULL,
  IncludedDescr varchar(254) default NULL,
  NotIncludedDescr varchar(254) default NULL,
  LocaleID int(11) NOT NULL default '0',
  PRIMARY KEY  (PriceListID)
) TYPE=InnoDB;

--
-- Table structure for table `servicedata`
--

CREATE TABLE servicedata (
  VitalsMasterKey int(11) NOT NULL default '0',
  FileVersion smallint(6) default NULL,
  OpenCloseBox char(1) default NULL,
  DayOfWeek varchar(9) default NULL,
  TimeOfService varchar(14) default NULL,
  PlaceOfService varchar(49) default NULL,
  PlaceOfServStreet varchar(29) default NULL,
  PlaceOfServCity varchar(39) default NULL,
  JewelryInstructions varchar(99) default NULL,
  Minister1 varchar(49) default NULL,
  Minister2 varchar(49) default NULL,
  Church varchar(49) default NULL,
  ChurchStreet varchar(29) default NULL,
  ChurchCityStZip varchar(39) default NULL,
  Organist varchar(49) default NULL,
  Soloist varchar(49) default NULL,
  Songs varchar(149) default NULL,
  CemeteryName varchar(49) default NULL,
  CemeteryStreet varchar(29) default NULL,
  CemeteryCity varchar(29) default NULL,
  CemeteryState varchar(14) default NULL,
  CemeteryZip varchar(10) default NULL,
  CemeteryCounty varchar(19) default NULL,
  CemeterySection varchar(29) default NULL,
  CemeteryLot varchar(19) default NULL,
  CemeteryGrave varchar(9) default NULL,
  CemeterySpace varchar(9) default NULL,
  TentEquipment char(1) default NULL,
  SetSeal char(1) default NULL,
  VaultManufacturer varchar(29) default NULL,
  VaultName varchar(29) default NULL,
  VaultCost int(11) default NULL,
  CasketManufacturer varchar(29) default NULL,
  CasketName varchar(29) default NULL,
  CasketCost int(11) default NULL,
  Autos varchar(149) default NULL,
  PickUpFamily varchar(49) default NULL,
  PickUpFamilyTime varchar(10) default NULL,
  CertifiedCopies smallint(6) default NULL,
  CertifiedsSendTo varchar(79) default NULL,
  Visitation varchar(199) default NULL,
  SpecialService varchar(199) default NULL,
  Restoration char(1) default NULL,
  HairStyle varchar(29) default NULL,
  Donations varchar(199) default NULL,
  CardStyle varchar(24) default NULL,
  CardCount smallint(6) default NULL,
  MemorialStyle varchar(24) default NULL,
  MemorialCount smallint(6) default NULL,
  FlowerDescription varchar(199) default NULL,
  FlowerSupplier varchar(199) default NULL,
  FlowerDelivery char(1) default NULL,
  FlowerPickup char(1) default NULL,
  SpecialInstructions varchar(199) default NULL,
  CremainsDisposition varchar(79) default NULL,
  CemeteryPhone varchar(19) default NULL,
  Minister1_addr varchar(29) default NULL,
  Minister1_citySt varchar(29) default NULL,
  Minister1_Salutation varchar(19) default NULL,
  Minister1_Phone varchar(19) default NULL,
  Minister2_addr varchar(29) default NULL,
  Minister2_citySt varchar(29) default NULL,
  Minister2_Salutation varchar(19) default NULL,
  Minister2_Phone varchar(19) default NULL,
  CemeteryTime varchar(10) default NULL,
  GraveSize varchar(24) default NULL,
  GraveDigger varchar(24) default NULL,
  StoneMason varchar(24) default NULL,
  ReopenGrave varchar(24) default NULL,
  BodySize varchar(24) default NULL,
  Dressed varchar(24) default NULL,
  Handles varchar(24) default NULL,
  Lining varchar(13) default NULL,
  memorialID int(11) NOT NULL default '0',
  CrematoryName varchar(49) default NULL,
  CrematoryStreet varchar(29) default NULL,
  CrematoryCity varchar(29) default NULL,
  CrematoryState varchar(14) default NULL,
  CrematoryZip varchar(10) default NULL,
  CremationDateOfService varchar(8) default NULL,
  PRIMARY KEY  (VitalsMasterKey)
) TYPE=InnoDB;

--
-- Table structure for table `speeddata`
--

CREATE TABLE speeddata (
  Identity int(11) NOT NULL auto_increment,
  TabCategory varchar(15) NOT NULL default '',
  Locale int(11) NOT NULL default '0',
  TabData varchar(254) NOT NULL default '',
  SortSequence int(11) default '0',
  PRIMARY KEY  (Identity)
) TYPE=InnoDB;

--
-- Table structure for table `survivors`
--

CREATE TABLE survivors (
  VitalsMasterKey int(11) default NULL,
  LastName varchar(49) default NULL,
  FirstName varchar(49) default NULL,
  Relation varchar(19) default NULL,
  Address varchar(39) default NULL,
  City varchar(32) default NULL,
  State char(2) default NULL,
  ZipCode varchar(9) default NULL,
  DateModified date default NULL,
  TimeModified time default NULL,
  AutoIndex int(11) NOT NULL auto_increment,
  SequenceNumber smallint(6) default NULL,
  VoidedCode char(1) default NULL,
  FileVersion smallint(6) default NULL,
  Phone varchar(19) default NULL,
  PRIMARY KEY  (AutoIndex),
  KEY VitalsKeyIndex (VitalsMasterKey),
  KEY NameIndex (LastName,FirstName)
) TYPE=InnoDB;

--
-- Table structure for table `tempPnCharges65`
--

CREATE TABLE tempPnCharges65 (
  ContractID int(11) default NULL,
  ChargeType smallint(6) default NULL,
  Description varchar(50) default NULL,
  Amount int(11) default NULL,
  Sequence smallint(6) default NULL,
  SPFcode char(1) NOT NULL default '',
  PriceListId int(11) default NULL,
  InvMasterKey int(11) default NULL,
  CategoryCode char(1) default NULL,
  AutoIndex int(10) unsigned NOT NULL auto_increment,
  TaxCode varchar(15) default NULL,
  TaxExemptAmt int(11) default NULL,
  sessionAction int(11) default '0',
  PRIMARY KEY  (AutoIndex)
) TYPE=InnoDB;

--
-- Table structure for table `transactionhistory`
--

CREATE TABLE transactionhistory (
  VitalsMasterKey int(11) NOT NULL default '0',
  TranHistID int(11) NOT NULL auto_increment,
  ChargeType smallint(6) default NULL,
  Description varchar(39) default NULL,
  AmountOfTran int(11) default NULL,
  ARacct varchar(10) default NULL,
  GLacct varchar(10) default NULL,
  TaxExemptAmount int(11) default NULL,
  TaxCode varchar(4) default NULL,
  DateOfTran varchar(8) default NULL,
  AccountingPeriod varchar(4) default NULL,
  SPFcode char(1) NOT NULL default '',
  ItemCategory char(1) default NULL,
  ReceiptNumber int(11) default NULL,
  Postedyn char(1) default NULL,
  OriginalPostingYN char(1) default NULL,
  DeleteTransaction char(1) default NULL,
  InventoryItemName varchar(14) default NULL,
  InvMasterKey int(11) default NULL,
  InvCostOfSale int(11) default NULL,
  PaymentMethod char(2) default NULL,
  PaymentComponent char(3) default NULL,
  UserInitials char(3) default NULL,
  ManualReceiptNo varchar(9) default NULL,
  RecordVersion smallint(6) default NULL,
  InterfaceSequenceNo int(11) default NULL,
  OrigChrgAmount int(11) default NULL,
  OrigChrgDescr varchar(39) default NULL,
  Exported char(1) default NULL,
  DateModified date default NULL,
  TimeModified time default NULL,
  DatePaid varchar(8) default NULL,
  DepositBatchNumber varchar(9) default NULL,
  ClaimNumber varchar(18) default NULL,
  locationId int(11) default NULL,
  InvOnHandID int(11) NOT NULL default '0',
  PRIMARY KEY  (TranHistID),
  KEY VitalsKeyIndex (VitalsMasterKey)
) TYPE=InnoDB;

--
-- Table structure for table `veteransinfo`
--

CREATE TABLE veteransinfo (
  VitalsMasterKey int(11) NOT NULL default '0',
  FlagVetName varchar(49) default NULL,
  FlagArmyBox smallint(6) default NULL,
  FlagNavyBox smallint(6) default NULL,
  FlagAirForceBox smallint(6) default NULL,
  FlagMarineBox smallint(6) default NULL,
  FlagCoastGuardBox smallint(6) default NULL,
  FlagOtherBranchBox smallint(6) default NULL,
  FlagSpanAmerBox smallint(6) default NULL,
  FlagWWIBox smallint(6) default NULL,
  FlagWWIIBox smallint(6) default NULL,
  FlagKoreanBox smallint(6) default NULL,
  FlagAfter55Box smallint(6) default NULL,
  FlagVietnamBox smallint(6) default NULL,
  FlagOtherServBox smallint(6) default NULL,
  FlagCondition1Box smallint(6) default NULL,
  FlagCondition2Box smallint(6) default NULL,
  FlagCondition3Box smallint(6) default NULL,
  FlagCondition4Box smallint(6) default NULL,
  FlagPersonReceive varchar(49) default NULL,
  FlagReceivRelation varchar(19) default NULL,
  FlagReceivAddress1 varchar(29) default NULL,
  FlagReceivAddress2 varchar(29) default NULL,
  FlagVAFileNumber varchar(20) default NULL,
  FlagSocSecNumber varchar(10) default NULL,
  FlagSerialNumber varchar(20) default NULL,
  FlagEnlistmentDate varchar(8) default NULL,
  FlagDischargeDate varchar(8) default NULL,
  FlagBirthDate varchar(8) default NULL,
  FlagDeathDate varchar(8) default NULL,
  FlagBurialDate varchar(8) default NULL,
  FlagBurialPlace varchar(79) default NULL,
  FlagRemarks varchar(79) default NULL,
  FlagAppAddress1 varchar(29) default NULL,
  FlagAppAddress2 varchar(29) default NULL,
  FlagAppRelation varchar(19) default NULL,
  FlagAppDate varchar(8) default NULL,
  Ben1ClaimantName varchar(49) default NULL,
  Ben1ClaimantStreet varchar(29) default NULL,
  Ben1ClaimCityStZip varchar(29) default NULL,
  Ben1PlaceBirth varchar(79) default NULL,
  Ben1PlaceDeath varchar(79) default NULL,
  Ben1BurialDate varchar(8) default NULL,
  Ben1DateEntered1 varchar(8) default NULL,
  Ben1PlaceEntered1 varchar(49) default NULL,
  Ben1ServiceNumber1 varchar(19) default NULL,
  Ben1SepSrvcDate1 varchar(8) default NULL,
  Ben1SepSrvcPlace1 varchar(49) default NULL,
  Ben1GradeRank1 varchar(79) default NULL,
  Ben1DateEntered2 varchar(8) default NULL,
  Ben1PlaceEntered2 varchar(49) default NULL,
  Ben1ServiceNumber2 varchar(19) default NULL,
  Ben1SepSrvcDate2 varchar(8) default NULL,
  Ben1SepSrvcPlace2 varchar(49) default NULL,
  Ben1GradeRank2 varchar(79) default NULL,
  Ben1DateEntered3 varchar(8) default NULL,
  Ben1PlaceEntered3 varchar(49) default NULL,
  Ben1ServiceNumber3 varchar(19) default NULL,
  Ben1SepSrvcDate3 varchar(8) default NULL,
  Ben1SepSrvcPlace3 varchar(49) default NULL,
  Ben1GradeRank3 varchar(79) default NULL,
  Ben1Box8OtherName varchar(79) default NULL,
  Ben1Box9Yes smallint(6) default NULL,
  Ben1Box9No smallint(6) default NULL,
  Ben1BurialPlace varchar(79) default NULL,
  Ben1Box11Yes smallint(6) default NULL,
  Ben1Box11No smallint(6) default NULL,
  Ben1Box12Yes smallint(6) default NULL,
  Ben1Box12No smallint(6) default NULL,
  Ben1Box13OtherPers smallint(6) default NULL,
  Ben1Box13DueFD smallint(6) default NULL,
  Ben1Box13DueCemet smallint(6) default NULL,
  Ben1Box13PaidClaim smallint(6) default NULL,
  Ben1Box13None smallint(6) default NULL,
  Ben1Box14NameAddr varchar(79) default NULL,
  Ben1Box15TotBurExp int(11) default NULL,
  Ben1Box16AmtPaid int(11) default NULL,
  Ben1Box17WhoseFund varchar(79) default NULL,
  Ben1Box18aYes smallint(6) default NULL,
  Ben1Box18aNo smallint(6) default NULL,
  Ben1Box18bAmtReimb int(11) default NULL,
  Ben1Box18cSrcReimb varchar(79) default NULL,
  Ben1Box19aYes smallint(6) default NULL,
  Ben1Box19aNo smallint(6) default NULL,
  Ben1Box19bAmount int(11) default NULL,
  Ben1Box19cSource varchar(79) default NULL,
  Ben1Box20Yes smallint(6) default NULL,
  Ben1Box20No smallint(6) default NULL,
  Ben2Box21 varchar(9) default NULL,
  Ben2Box22Place1 varchar(49) default NULL,
  Ben2Box22Place2 varchar(49) default NULL,
  Ben2Box23aCost int(11) default NULL,
  Ben2Box23bDatePurc varchar(8) default NULL,
  Ben2Box23cDatePay varchar(8) default NULL,
  Ben2Box24aYes smallint(6) default NULL,
  Ben2Box24aNo smallint(6) default NULL,
  Ben2Box24bAmtPaid int(11) default NULL,
  Ben2Box25WhoseFund varchar(49) default NULL,
  Ben2Box26aYes smallint(6) default NULL,
  Ben2Box26aNo smallint(6) default NULL,
  Ben2Box26bAmount int(11) default NULL,
  Ben2Box26cSource varchar(49) default NULL,
  Ben2Box27aYes smallint(6) default NULL,
  Ben2Box27aNo smallint(6) default NULL,
  Ben2Box27bAmount int(11) default NULL,
  Ben2Box27cSource varchar(49) default NULL,
  Ben2Box28bOfficPos varchar(49) default NULL,
  Ben2Box29Agency varchar(79) default NULL,
  Ben2Box30bName varchar(69) default NULL,
  Ben2Box31Address varchar(79) default NULL,
  Ben2Box32Date varchar(8) default NULL,
  Ben2Box33Relation varchar(49) default NULL,
  HeadFirstName varchar(14) default NULL,
  HeadMiddleName varchar(14) default NULL,
  HeadLastName varchar(24) default NULL,
  HeadBox2Yes smallint(6) default NULL,
  HeadBox2No smallint(6) default NULL,
  HeadBranchArmy smallint(6) default NULL,
  HeadBranchNavy smallint(6) default NULL,
  HeadBranchAirForce smallint(6) default NULL,
  HeadBranchMarines smallint(6) default NULL,
  HeadBranchCoastGua smallint(6) default NULL,
  HeadBranchArmyAir smallint(6) default NULL,
  HeadBranchOther smallint(6) default NULL,
  HeadBranchSpecify varchar(39) default NULL,
  HeadValorMOH smallint(6) default NULL,
  HeadValorDSC smallint(6) default NULL,
  HeadValorNC smallint(6) default NULL,
  HeadValorAFC smallint(6) default NULL,
  HeadValorSS smallint(6) default NULL,
  HeadValorPH smallint(6) default NULL,
  HeadWarWWI smallint(6) default NULL,
  HeadWarWWII smallint(6) default NULL,
  HeadWarKorean smallint(6) default NULL,
  HeadWarVietnam smallint(6) default NULL,
  HeadWarOther smallint(6) default NULL,
  HeadWarSpecify varchar(29) default NULL,
  HeadStoneBronze smallint(6) default NULL,
  HeadStoneGranite smallint(6) default NULL,
  HeadStoneUpright smallint(6) default NULL,
  HeadStoneFlat smallint(6) default NULL,
  HeadBeliefChrist smallint(6) default NULL,
  HeadBeliefBuddhist smallint(6) default NULL,
  HeadBeliefJewish smallint(6) default NULL,
  HeadBeliefOther smallint(6) default NULL,
  HeadBeliefSpecify varchar(39) default NULL,
  HeadAppNameAddress varchar(79) default NULL,
  HeadRelationship varchar(19) default NULL,
  HeadAppPhoneNumber varchar(19) default NULL,
  HeadGraveID varchar(39) default NULL,
  HeadGraveSection varchar(39) default NULL,
  HeadGraveNumber varchar(39) default NULL,
  HeadPrivCemeteryID varchar(39) default NULL,
  HeadConsignNameAddr varchar(79) default NULL,
  HeadCemeteryPhone varchar(19) default NULL,
  HeadCemNameAddress varchar(79) default NULL,
  HeadRemarks varchar(79) default NULL,
  HeadHighestRank varchar(19) default NULL,
  StoneNiche smallint(6) default NULL,
  StoneUprightGranite smallint(6) default NULL,
  Ben1DayPhone varchar(19) default NULL,
  Ben1NightPhone varchar(19) default NULL,
  DateModified date default NULL,
  TimeModified time default NULL,
  HeadBranchMerchMarine smallint(6) NOT NULL default '0',
  HeadValorBSM smallint(6) NOT NULL default '0',
  HeadWarPG smallint(6) NOT NULL default '0',
  HeadBeliefNone smallint(6) NOT NULL default '0',
  FlagVetOtherName varchar(30) default NULL,
  FlagSelServiceBox smallint(6) default NULL,
  FlagGulfBox smallint(6) default NULL,
  FlagCond5Box smallint(6) default NULL,
  FlagOtherVetService varchar(60) default NULL,
  FlagOtherBranchOfService varchar(60) default NULL,
  HeadSuffix varchar(10) default NULL,
  HeadAppFax varchar(14) default NULL,
  HeadAppEmail varchar(40) default NULL,
  HeadRequestInitial tinyint(3) default NULL,
  HeadRequestSecond tinyint(3) default NULL,
  HeadRequestCorrected tinyint(3) default NULL,
  HeadValorOther tinyint(3) default NULL,
  HeadValorOtherSpecify varchar(29) default NULL,
  HeadRelOther tinyint(3) default NULL,
  HeadRelOtherSpecify varchar(29) default NULL,
  HeadGraveMarked tinyint(3) default NULL,
  PRIMARY KEY  (VitalsMasterKey)
) TYPE=InnoDB;

--
-- Table structure for table `vitalstats`
--

CREATE TABLE vitalstats (
  ChapelLocation varchar(19) default NULL,
  DeathDateKey varchar(8) NOT NULL default '00000000',
  ServiceDateKey varchar(8) NOT NULL default '00000000',
  SaleDateKey varchar(8) default NULL,
  InterfacedCode char(1) default NULL,
  ArrangerId int(11) default NULL,
  CaseCode varchar(8) NOT NULL default '',
  ContractCode varchar(10) NOT NULL default '',
  StateOfDeath char(2) default NULL,
  VitalsCompleted smallint(6) default NULL,
  ServicesCompleted smallint(6) default NULL,
  FinancialsCompleted smallint(6) default NULL,
  VeteransCompleted smallint(6) default NULL,
  ObitCompleted smallint(6) default NULL,
  CustomCompleted smallint(6) default NULL,
  PaymentsCompleted smallint(6) default NULL,
  StmtSentDate varchar(8) default NULL,
  MiscCheckBxDesc1 varchar(15) default NULL,
  MiscCheckBxDesc2 varchar(15) default NULL,
  MiscCheckBxDesc3 varchar(15) default NULL,
  MiscCheckBxDesc4 varchar(15) default NULL,
  MiscCheckBxDesc5 varchar(15) default NULL,
  MiscCheckBxDesc6 varchar(15) default NULL,
  MiscCheckBxDesc7 varchar(15) default NULL,
  MiscCheckBxDesc8 varchar(15) default NULL,
  MiscCheckBxDesc9 varchar(15) default NULL,
  MiscCheckBxDesc10 varchar(15) default NULL,
  MiscCheckBxDesc11 varchar(15) default NULL,
  MiscCheckBxDesc12 varchar(15) default NULL,
  MiscCheckBxDesc13 varchar(15) default NULL,
  MiscCheckBxDesc14 varchar(15) default NULL,
  MiscCheckBxDesc15 varchar(15) default NULL,
  MiscCheckBxDesc16 varchar(15) default NULL,
  MiscChecked1 smallint(6) default NULL,
  MiscChecked2 smallint(6) default NULL,
  MiscChecked3 smallint(6) default NULL,
  MiscChecked4 smallint(6) default NULL,
  MiscChecked5 smallint(6) default NULL,
  MiscChecked6 smallint(6) default NULL,
  MiscChecked7 smallint(6) default NULL,
  MiscChecked8 smallint(6) default NULL,
  MiscChecked9 smallint(6) default NULL,
  MiscChecked10 smallint(6) default NULL,
  MiscChecked11 smallint(6) default NULL,
  MiscChecked12 smallint(6) default NULL,
  MiscChecked13 smallint(6) default NULL,
  MiscChecked14 smallint(6) default NULL,
  MiscChecked15 smallint(6) default NULL,
  MiscChecked16 smallint(6) default NULL,
  VitalsMasterKey int(11) NOT NULL auto_increment,
  PreneedBox smallint(6) default NULL,
  CompanyNumber varchar(4) default NULL,
  ArrangerNumber char(3) default NULL,
  ContractNumber int(11) default NULL,
  FirstCallCompleted smallint(6) default NULL,
  RecordVersion smallint(6) default NULL,
  DateAdded varchar(8) default NULL,
  DatePosted varchar(8) default NULL,
  DonationsCompleted smallint(6) default NULL,
  DecMrMrs varchar(4) default NULL,
  AppointmentTime varchar(9) default NULL,
  DeceasedFirstName varchar(14) NOT NULL default '',
  DeceasedSuffix varchar(14) default NULL,
  DeceasedLastName varchar(24) NOT NULL default '',
  DeceasedSex char(1) default NULL,
  DateOfDeath varchar(8) default NULL,
  AgeYears smallint(6) default NULL,
  AgeMonths smallint(6) default NULL,
  AgeDays smallint(6) default NULL,
  AgeHours smallint(6) default NULL,
  AgeMinutes smallint(6) default NULL,
  DateOfBirth varchar(8) default NULL,
  CountyOfDeath varchar(29) default NULL,
  LocationOfDeath varchar(100) default NULL,
  InpatientDOA varchar(19) default NULL,
  InpatientDate varchar(8) default NULL,
  CityOfDeath varchar(29) default NULL,
  SocialSecurityNo varchar(10) default NULL,
  Occupation varchar(49) default NULL,
  KindOfBusiness varchar(49) default NULL,
  FirmName varchar(49) default NULL,
  DecResState varchar(19) default NULL,
  DecResCounty varchar(19) default NULL,
  DecCityTwpBox char(1) default NULL,
  DecCityTwpName varchar(29) default NULL,
  DecResMailCity varchar(29) default NULL,
  DecResStreet varchar(29) default NULL,
  DecResZip varchar(10) default NULL,
  DecResCountry varchar(30) default NULL,
  DecResInsideCity char(1) default NULL,
  DecBirthPlace varchar(50) default NULL,
  DecMarried varchar(14) default NULL,
  SurvSpouseMaiden varchar(49) default NULL,
  SpouseFirstName varchar(14) default NULL,
  SpouseMiddleName varchar(14) default NULL,
  SpouseLastName varchar(19) default NULL,
  InArmedForces char(1) default NULL,
  Ancestry varchar(29) default NULL,
  HispanicOriginBox char(1) default NULL,
  Race varchar(14) default NULL,
  ElementaryEduc char(3) default NULL,
  CollegeEducation char(3) default NULL,
  FathersName varchar(49) default NULL,
  MothersName varchar(49) default NULL,
  InformantFirstName varchar(24) default NULL,
  InformantLastName varchar(24) default NULL,
  InformantStreet varchar(29) default NULL,
  InformantCity varchar(29) default NULL,
  InformantState varchar(19) default NULL,
  InformantZip varchar(10) default NULL,
  InformantRelation varchar(19) default NULL,
  InformantMiddleNam varchar(14) default NULL,
  DispositionMethod varchar(19) default NULL,
  DispositionPlace varchar(39) default NULL,
  DispositionStreet varchar(29) default NULL,
  DispositionCity varchar(29) default NULL,
  DispositionState varchar(19) default NULL,
  DispositionZip varchar(10) default NULL,
  DispositionDate varchar(8) default NULL,
  BurialDate varchar(8) default NULL,
  DirectorLicenseNo varchar(15) default NULL,
  EmbalmerLicenseNo varchar(15) default NULL,
  FacilityName varchar(49) default NULL,
  FacilityStreet varchar(29) default NULL,
  FacilityCityStZip varchar(39) default NULL,
  FacilityLicenseNo varchar(15) default NULL,
  DecAptNo varchar(15) default NULL,
  CauseOfDeath1 varchar(49) default NULL,
  CauseOfDeath2 varchar(49) default NULL,
  CauseOfDeath3 varchar(49) default NULL,
  CauseOfDeath4 varchar(49) default NULL,
  CauseInterval1 varchar(14) default NULL,
  CauseInterval2 varchar(14) default NULL,
  CauseInterval3 varchar(14) default NULL,
  CauseInterval4 varchar(14) default NULL,
  OtherConditions varchar(49) default NULL,
  Autopsy char(1) default NULL,
  AutopsyFindings char(1) default NULL,
  AutopsyDoneWhere varchar(49) default NULL,
  OperationDate varchar(8) default NULL,
  OperationFindings varchar(49) default NULL,
  PregnantAtDeath char(1) default NULL,
  PregnantLast12mos char(1) default NULL,
  ActualPlaceDeath varchar(19) default NULL,
  ReferredToME char(1) default NULL,
  DateSigned varchar(8) default NULL,
  TimeOfDeath varchar(10) default NULL,
  MEcheckBox smallint(6) default NULL,
  MEdateSigned varchar(8) default NULL,
  MEcaseNumber varchar(14) default NULL,
  MEpronounDeadDate varchar(8) default NULL,
  MEpronounDeadTime varchar(10) default NULL,
  MELicenseNumber varchar(15) default NULL,
  AttendingPhysician varchar(49) default NULL,
  DoctorName varchar(49) default NULL,
  DoctorStreet varchar(29) default NULL,
  DoctorCity varchar(29) default NULL,
  DoctorState varchar(14) default NULL,
  DoctorZip varchar(10) default NULL,
  DoctorLicenseNumber varchar(14) default NULL,
  AccidSuicideNaturl varchar(24) default NULL,
  InjuryDate varchar(8) default NULL,
  InjuryTime varchar(10) default NULL,
  InjuryDescription varchar(59) default NULL,
  InjuryAtWork char(1) default NULL,
  InjuryPlace varchar(49) default NULL,
  InjuryStreet varchar(29) default NULL,
  InjuryCityState varchar(29) default NULL,
  EmbalmingReason varchar(29) default NULL,
  EmbalmingChargeReq varchar(30) default NULL,
  DateFDnotified varchar(8) default NULL,
  TimeFDnotified varchar(10) default NULL,
  VoidedCode char(1) default NULL,
  PreneedCasketName varchar(29) default NULL,
  PreneedVaultName varchar(29) default NULL,
  PreneedUrnName varchar(29) default NULL,
  PreneedServiceType varchar(29) default NULL,
  PNServiceAmt int(11) default NULL,
  PNCasketAmt int(11) default NULL,
  PNVaultAmt int(11) default NULL,
  PNUrnAmt int(11) default NULL,
  PNOtherAmt int(11) default NULL,
  PreneedArrngDate varchar(8) default NULL,
  FatherFirstName varchar(14) default NULL,
  FatherMiddleName varchar(14) default NULL,
  FatherLastName varchar(19) default NULL,
  PNBeneSameBuyer char(1) default NULL,
  NextKinFirstName varchar(14) default NULL,
  NextKinLastName varchar(14) default NULL,
  NextKinSalutation varchar(19) default NULL,
  ChapelNumber int(11) default NULL,
  NextKinRelation varchar(19) default NULL,
  NextKinSameAsInf char(1) default NULL,
  LocaleNumber int(11) default NULL,
  Salutation varchar(30) default NULL,
  MotherFirstName varchar(14) default NULL,
  MotherMiddleName varchar(14) default NULL,
  MotherLastName varchar(19) default NULL,
  BurialPermitNumber varchar(10) default NULL,
  CountyOfIssue varchar(20) default NULL,
  IssueDate varchar(8) default NULL,
  EmployerCode char(2) default NULL,
  WarFromDate varchar(8) default NULL,
  WarToDate varchar(8) default NULL,
  EmployerAddress varchar(57) default NULL,
  YearsAtOccupation smallint(6) default NULL,
  DeathInsideCity char(1) default NULL,
  LocOfDeathStreet varchar(29) default NULL,
  Citizenship varchar(24) default NULL,
  LocOfDeathCVT char(1) default NULL,
  MedicalRecordNumber varchar(20) default NULL,
  TransferredYN char(1) default NULL,
  TransferredLocation varchar(59) default NULL,
  BirthHospital varchar(29) default NULL,
  DeceasedFullName varchar(39) default NULL,
  EmbalmerName varchar(29) default NULL,
  DeathOnFarm char(1) default NULL,
  ReportedInService varchar(10) default NULL,
  MilitaryOrganizatn varchar(15) default NULL,
  VetSerialNumber varchar(20) default NULL,
  DeceasedMaidenName varchar(39) default NULL,
  LoctnOfDeathZip varchar(10) default NULL,
  NextKinCity varchar(29) default NULL,
  MotherBirthCity varchar(30) default NULL,
  NextOfKinAddress varchar(34) default NULL,
  FatherBirthCity varchar(30) default NULL,
  SpouseAge varchar(5) default NULL,
  HairColor varchar(14) default NULL,
  EyeColor varchar(14) default NULL,
  HeightFeet smallint(6) default NULL,
  HeightInches smallint(6) default NULL,
  Weight smallint(6) default NULL,
  Deformities varchar(34) default NULL,
  FatherBirthState varchar(19) default NULL,
  FatherBirthCountry varchar(20) default NULL,
  Tattoos varchar(29) default NULL,
  MotherBirthState varchar(19) default NULL,
  MotherBirthCountry varchar(20) default NULL,
  IdentificationMarks varchar(30) default NULL,
  BiopsyYN char(1) default NULL,
  TimeAtResidence varchar(9) default NULL,
  Tobacco char(1) default NULL,
  OrganDonationConside char(1) default NULL,
  OrganDonationGranted char(1) default NULL,
  PNBuyerTitle varchar(10) default NULL,
  PNBuyerFirstName varchar(14) default NULL,
  PNBuyerMidName varchar(14) default NULL,
  PNBuyerLastName varchar(24) default NULL,
  PNBuyerStreet varchar(29) default NULL,
  PNBuyerAptNo varchar(15) default NULL,
  PNBuyerCity varchar(29) default NULL,
  PNBuyerState varchar(19) default NULL,
  PNBuyerZip varchar(10) default NULL,
  PNCobuyer varchar(39) default NULL,
  PNBuyerSSno varchar(12) default NULL,
  PNCounselor varchar(39) default NULL,
  PNPreneedStatus char(1) default NULL,
  PNFundType varchar(24) default NULL,
  PNDepository varchar(29) default NULL,
  PNContractDate varchar(8) default NULL,
  PNMaturityDate varchar(8) default NULL,
  PNFundAcctNo varchar(24) default NULL,
  PNInterestRate double default NULL,
  PNFundsAccessable char(1) default NULL,
  PNContractAmount int(11) default NULL,
  PNPaidYTD int(11) default NULL,
  PNPaidTotal int(11) default NULL,
  PNYTDInterest int(11) default NULL,
  PNTotalInterest int(11) default NULL,
  PNMgmtFee int(11) default NULL,
  PNCommission int(11) default NULL,
  PNFaceValue int(11) default NULL,
  PNLastPmtAmount int(11) default NULL,
  PNLastPmtDate varchar(8) default NULL,
  PNSource varchar(19) default NULL,
  ShippingData varchar(106) default NULL,
  DeceasedMidName varchar(29) default NULL,
  NextKinState varchar(19) default NULL,
  NextKinZip varchar(10) default NULL,
  InterestFromDate varchar(8) default NULL,
  MarketingPlan varchar(24) default NULL,
  CheckListDate1 varchar(8) default NULL,
  CheckListDate2 varchar(8) default NULL,
  CheckListDate3 varchar(8) default NULL,
  CheckListDate4 varchar(8) default NULL,
  CheckListDate5 varchar(8) default NULL,
  CheckListDate6 varchar(8) default NULL,
  CheckListDate7 varchar(8) default NULL,
  CheckListDate8 varchar(8) default NULL,
  DispositionCode varchar(20) default NULL,
  VoidedFromContract varchar(9) default NULL,
  VoidedToContract varchar(9) default NULL,
  DirectorName varchar(29) default NULL,
  BirthSurname varchar(24) default NULL,
  BirthGivenNames varchar(44) default NULL,
  OriginalPNDate varchar(8) default NULL,
  BuyerMrMrs varchar(4) default NULL,
  BuyerBirthDate varchar(8) default NULL,
  InformantPhone varchar(20) default NULL,
  FacilityPhone varchar(20) default NULL,
  DoctorPhone varchar(20) default NULL,
  DoctorFax varchar(20) default NULL,
  NextKinPhone varchar(20) default NULL,
  Doctor2Name varchar(49) default NULL,
  Doctor2Addr varchar(29) default NULL,
  Doctor2City varchar(29) default NULL,
  Doctor2State varchar(14) default NULL,
  Doctor2Zip varchar(10) default NULL,
  Doctor2Phone varchar(20) default NULL,
  InformantRoad2 varchar(24) default NULL,
  InformantRoad3 varchar(24) default NULL,
  NextKinRoad2 varchar(24) default NULL,
  NextKinRoad3 varchar(24) default NULL,
  DonationAdmin varchar(24) default NULL,
  DateModified date default NULL,
  TimeModified time default NULL,
  CallDate varchar(8) default NULL,
  CallTime varchar(10) default NULL,
  InformantEmail varchar(50) default NULL,
  EmbalmerID int(11) default '0',
  DecAliasFirst varchar(15) default NULL,
  DecAliasMiddle varchar(15) default NULL,
  DecAliasLast varchar(25) default NULL,
  DecAliasPrefix varchar(15) default NULL,
  DecAliasSuffix varchar(15) default NULL,
  crematoryName varchar(30) default NULL,
  DoctorTitle varchar(10) default NULL,
  DoctorAttendFrom date default NULL,
  DoctorAttendTo date default NULL,
  DoctorAttendLast date default NULL,
  DoctorViewedBody char(1) default NULL,
  InjuryTransportation varchar(100) default NULL,
  LocalityUnincorporated char(1) default NULL,
  DecEducation varchar(200) default NULL,
  DecSpecifyHispanic varchar(200) default NULL,
  TribalReservation varchar(200) default NULL,
  DateCertified varchar(8) default NULL,
  InformantDateSigned varchar(8) default NULL,
  FuneralDirectorDateSigned varchar(8) default NULL,
  BurialPermitIssuer varchar(200) default NULL,
  PlaceOfIssue varchar(100) default NULL,
  BurialIssuedDate varchar(8) default NULL,
  RegistrationNumber varchar(100) default NULL,
  RegCodeNumber varchar(100) default NULL,
  RegistrarFileDate varchar(8) default NULL,
  CremationAuthorizer varchar(100) default NULL,
  DiagnosisDeferred char(1) default NULL,
  InjuryOccurred char(1) default NULL,
  CustomerName varchar(50) default NULL,
  Comments text,
  DateEmbalmed varchar(8) default NULL,
  PRIMARY KEY  (VitalsMasterKey)
) TYPE=InnoDB;
