package fdms.info;

import java.util.HashMap;
import java.util.Map;

public class ColumnMapping {
	private Map<String, Integer> columnMapping = new HashMap<String, Integer>();
	private Map<String, Integer> preNeedColumnMapping = new HashMap<String, Integer>();
	
	private static ColumnMapping instance = null;
	
	private ColumnMapping(int val) {
		preNeedColumnMapping.put("buyerTitle",1);
		preNeedColumnMapping.put("buyerFirst",2);
		preNeedColumnMapping.put("buyerMiddle",3);
		preNeedColumnMapping.put("buyerLast",4);
		preNeedColumnMapping.put("buyerStreet",5);
		preNeedColumnMapping.put("buyerCity",7);
		preNeedColumnMapping.put("buyerState",8);
		preNeedColumnMapping.put("buyerZipCode",9);
		preNeedColumnMapping.put("buyerPhone",10);
		preNeedColumnMapping.put("buyerSocialSecurityNumber",11);
		preNeedColumnMapping.put("coBuyerName",12);
		preNeedColumnMapping.put("beneficiaryFirst",14);
		preNeedColumnMapping.put("beneficiaryMiddle",15);
		preNeedColumnMapping.put("beneficiaryLast",16);
		preNeedColumnMapping.put("beneficiaryStreet", 17);
		preNeedColumnMapping.put("beneficiaryCity", 19);
		preNeedColumnMapping.put("beneficiaryState",20);
		preNeedColumnMapping.put("beneficiaryZipCode",21);
		preNeedColumnMapping.put("beneficiarySocialSecurityNumber",23);
		preNeedColumnMapping.put("beneficiaryDOB",24);
		preNeedColumnMapping.put("saleDate",25);
		preNeedColumnMapping.put("caseNumber",26);
		preNeedColumnMapping.put("casket",27);
		preNeedColumnMapping.put("urn",28);
		preNeedColumnMapping.put("casketSale",29);
		preNeedColumnMapping.put("vaultSale",30);
		preNeedColumnMapping.put("gstAmt",31);
		preNeedColumnMapping.put("mortuaryLocation",32);
		preNeedColumnMapping.put("service",33);
		preNeedColumnMapping.put("vault",34);
		preNeedColumnMapping.put("serviceSale",35);
		preNeedColumnMapping.put("urnSale",36);
		preNeedColumnMapping.put("otherSale",37);
		preNeedColumnMapping.put("totalSale",38);
		preNeedColumnMapping.put("fundDepositoryType",39);
		preNeedColumnMapping.put("fundsWith",40);
		preNeedColumnMapping.put("fundsStreet",41);
		preNeedColumnMapping.put("fundsCity",42);
		preNeedColumnMapping.put("fundsState",43);
		preNeedColumnMapping.put("fundsZip",44);
		preNeedColumnMapping.put("dateStarted",45);
		preNeedColumnMapping.put("maturity",46);
		preNeedColumnMapping.put("accountNumber",47);
		preNeedColumnMapping.put("estIntRate",48);
		preNeedColumnMapping.put("fundsDepositedDate",49);
		preNeedColumnMapping.put("lastPaymentDate",50);
		preNeedColumnMapping.put("faceValue",51);
		preNeedColumnMapping.put("contractAmount",52);
		preNeedColumnMapping.put("ytdPaid",53);
		preNeedColumnMapping.put("totalPaid",54);
		preNeedColumnMapping.put("ytdInterest",55);
		preNeedColumnMapping.put("totalInterest",56);
		preNeedColumnMapping.put("managementFee",57);
		preNeedColumnMapping.put("commission",58);
		preNeedColumnMapping.put("lastPaymentAmount",59);
		preNeedColumnMapping.put("comments",60);
		preNeedColumnMapping.put("preneedStatus",61);
		preNeedColumnMapping.put("counselor",62);
		preNeedColumnMapping.put("source",64);

		columnMapping.put("preneedDate", 0);
		columnMapping.put("contractNumber", 1);
		columnMapping.put("caseNumber", 2);
		columnMapping.put("arrangeDate", 3);
		columnMapping.put("time", 4);
		columnMapping.put("chapel", 5);
		columnMapping.put("facility", 6);
		columnMapping.put("director", 7);
		columnMapping.put("source", 8);
		columnMapping.put("embalming", 9);
		columnMapping.put("prefix", 10);
		columnMapping.put("firstName", 11);
		columnMapping.put("middleName", 12);
		columnMapping.put("lastName", 13);
		columnMapping.put("suffix", 14);
		columnMapping.put("maidenName", 15);
		columnMapping.put("memorialName", 16);
		columnMapping.put("placeDeath", 17);
		columnMapping.put("locationDeceased", 18);
		columnMapping.put("placeDeathCity", 19);
		columnMapping.put("placeDeathState", 20);
		columnMapping.put("placeDeathZip", 21);
		columnMapping.put("locDeathLicenseNumber", 22);
		columnMapping.put("birthDate", 23);
		columnMapping.put("deathDate", 24);
		columnMapping.put("age", 25);
		columnMapping.put("serviceDate", 26);
		columnMapping.put("dispDate", 27);
		columnMapping.put("chapelName", 28);
		columnMapping.put("chapelStreet", 29);
		columnMapping.put("chapelCity", 30);
		columnMapping.put("chapelState", 31);
		columnMapping.put("chapelZip", 32);
		columnMapping.put("chapelPhone", 33);
		columnMapping.put("chapelLicense", 34);
		columnMapping.put("facilityName", 35);
		columnMapping.put("facilityStreet", 36);
		columnMapping.put("facilityCity", 37);
		columnMapping.put("facilityState", 38);
		columnMapping.put("facilityZip", 39);
		columnMapping.put("facilityPhone", 40);
		columnMapping.put("facilityLicense", 41);
		columnMapping.put("informantSalutation", 42);
		columnMapping.put("informantFirst", 43);
		columnMapping.put("informantMiddle", 44);
		columnMapping.put("informantLast", 45);
		columnMapping.put("informantRelation", 46);
		columnMapping.put("informantStreet", 47);
		columnMapping.put("informantStreet2", 48);
		columnMapping.put("informantStreet3", 49);
		columnMapping.put("informantCity", 50);
		columnMapping.put("informantState", 51);
		columnMapping.put("informantZip", 52);
		columnMapping.put("informantPhone", 53);
		columnMapping.put("informantCellPhone", 54);
		columnMapping.put("informantEmail", 55);
		columnMapping.put("informantPreferCommunicate", 56);
		columnMapping.put("informantBillToParty", 57);
		columnMapping.put("nextKinSalutation", 58);
		columnMapping.put("nextKinFirst", 59);
		columnMapping.put("nextKinMiddle", 60);
		columnMapping.put("nextKinLast", 61);
		columnMapping.put("nextKinRelation", 62);
		columnMapping.put("nextKinStreet", 63);
		columnMapping.put("nextKinStreet2", 64);
		columnMapping.put("nextKinStreet3", 65);
		columnMapping.put("nextKinCity", 66);
		columnMapping.put("nextKinState", 67);
		columnMapping.put("nextKinZip", 68);
		columnMapping.put("nextKinPhone", 69);
		columnMapping.put("nextKinCellPhone", 70);
		columnMapping.put("nextKinEmail", 71);
		columnMapping.put("nextKinPreferCommunicate", 72);
		columnMapping.put("executorFirstName", 73);
		columnMapping.put("executorLastName", 74);
		columnMapping.put("executorRelation", 75);
		columnMapping.put("executorStreet", 76);
		columnMapping.put("executorStreet2", 77);
		columnMapping.put("executorStreet3", 78);
		columnMapping.put("executorCity", 79);
		columnMapping.put("executorState", 80);
		columnMapping.put("executorZip", 81);
		columnMapping.put("executorPhone", 82);
		columnMapping.put("executorCellPhone", 83);
		columnMapping.put("executorEmail", 84);
		columnMapping.put("shippingInfo", 85);
		columnMapping.put("callInfoNote", 86);
		
		columnMapping.put("applyFinanceCharges", 88 + val);
		columnMapping.put("iterestRate", 89 + val);
		columnMapping.put("interestFromDate", 90 + val);
		columnMapping.put("customerName", 91 + val);
		columnMapping.put("sendToAccounting", 92 + val);
		columnMapping.put("saleDate", 93 + val);
		columnMapping.put("dueDate", 94 + val);
		columnMapping.put("stmtDate", 95 + val);
		columnMapping.put("amountPaid", 96 + val);
		columnMapping.put("paymentSource", 97 + val);
		columnMapping.put("dateOfPayment", 98 + val);
		columnMapping.put("dateOfDeposit", 99 + val);
		columnMapping.put("receiptNumber", 100 + val);
		columnMapping.put("manualReceiptNumber", 101 + val);
		columnMapping.put("nonCashAdjustment", 102 + val);
		columnMapping.put("methodOfPayment", 103 + val);
		columnMapping.put("saleType", 104 + val);
		columnMapping.put("source", 105 + val);
		columnMapping.put("disposition", 106 + val);
		columnMapping.put("servicePlan", 107 + val);
		columnMapping.put("providedServices", 108 + val);
		columnMapping.put("previousFuneralHomeUsed", 109 + val);
		columnMapping.put("advertisingSource", 110 + val);
		columnMapping.put("miscNotes", 111 + val);
		
		columnMapping.put("identificationMarks", 233 + val);
		columnMapping.put("deceasedFirstName", 234 + val);
		columnMapping.put("deceasedMiddleName", 235 + val);
		columnMapping.put("deceasedLastName", 236 + val);
		columnMapping.put("deceasedMaiden", 237 + val);
		columnMapping.put("decPrefix", 238 + val);
		columnMapping.put("deceasedSuffix", 239 + val);
		columnMapping.put("aliasFirstName", 240 + val);
		columnMapping.put("aliasMiddleName", 241 + val);
		columnMapping.put("aliasLastName", 242 + val);
		columnMapping.put("aliasPrefix", 243 + val);
		columnMapping.put("aliasSuffix", 244 + val);
		columnMapping.put("sex", 245 + val);
		columnMapping.put("dateOfBirth", 246 + val);
		columnMapping.put("dateOfDeath", 247 + val);
		columnMapping.put("ageYears", 248 + val);
		columnMapping.put("ageMonths", 249 + val);
		columnMapping.put("ageDays", 250 + val);
		columnMapping.put("ageHours", 251 + val);
		columnMapping.put("ageMinutes", 252 + val);
		columnMapping.put("locationOfDeath", 253 + val);
		columnMapping.put("locDeathLicenseNumber", 254 + val);
		columnMapping.put("cityOfDeath", 255 + val);
		columnMapping.put("countyOfDeath", 256 + val);
		columnMapping.put("deathInsideCity", 257 + val);
		columnMapping.put("locOfDeathCVT", 258 + val);
		columnMapping.put("deceasedStreet", 259 + val);
		columnMapping.put("localityInsideCity", 260 + val);
		columnMapping.put("localityInsideVillage", 261 + val);
		columnMapping.put("localityInsideTwp", 262 + val);
		columnMapping.put("localityUnincorporated", 263 + val);
		columnMapping.put("localityUnknown", 264 + val);
		columnMapping.put("deceasedCity2", 265 + val);
		columnMapping.put("deceasedCounty", 266 + val);
		columnMapping.put("deceasedState", 267 + val);
		columnMapping.put("deceasedZipCode", 268 + val);
		columnMapping.put("deceasedCountry", 269 + val);
		columnMapping.put("deceasedResLengthTime", 270 + val);
		columnMapping.put("birthplaceCity", 271 + val);
		columnMapping.put("birthplaceState", 272 + val);
		columnMapping.put("countyOfBirth", 273 + val);
		columnMapping.put("birthplaceCountry", 274 + val);
		columnMapping.put("socialSecurityNumber", 275 + val);
		columnMapping.put("decEducation", 276 + val);
		columnMapping.put("deceasedElementaryEducation", 277 + val);
		columnMapping.put("deceasedCollegeEducation", 278 + val);
		columnMapping.put("race", 279 + val);
		columnMapping.put("tribalMember", 280 + val);
		columnMapping.put("tribalName", 281 + val);
		columnMapping.put("hispanic", 282 + val);
		columnMapping.put("ancestry", 283 + val);
		columnMapping.put("citizenship", 284 + val);
		columnMapping.put("veteran", 285 + val);
		columnMapping.put("veteranDateEntered", 286 + val);
		columnMapping.put("veteranDateSeparated", 287 + val);
		columnMapping.put("deceasedOccupation", 288 + val);
		columnMapping.put("deceasedKindBusinessOrIndustry", 289 + val);
		columnMapping.put("employer", 290 + val);
		columnMapping.put("maritalStatus", 291 + val);
		columnMapping.put("survivingSpouse1", 292 + val);
		columnMapping.put("survivingSpouse2", 293 + val);
		columnMapping.put("survivingSpouse3", 294 + val);
		columnMapping.put("fatherFirstName", 295 + val);
		columnMapping.put("fatherMiddleName", 296 + val);
		columnMapping.put("fatherLastName", 297 + val);
		columnMapping.put("fatherBirthCity", 298 + val);
		columnMapping.put("fatherBirthState", 299 + val);
		columnMapping.put("motherFirstName", 300 + val);
		columnMapping.put("motherMiddleName", 301 + val);
		columnMapping.put("motherLastName", 302 + val);
		columnMapping.put("motherMaidenName", 303 + val);
		columnMapping.put("motherBirthCity", 304 + val);
		columnMapping.put("motherBirthState", 305 + val);
		columnMapping.put("informantFirstName", 306 + val);
		columnMapping.put("informantMiddleName", 307 + val);
		columnMapping.put("informantLastName", 308 + val);
		columnMapping.put("informantRelation", 309 + val);
		columnMapping.put("informantStreet", 310 + val);
		columnMapping.put("informantCity", 311 + val);
		columnMapping.put("informantState", 312 + val);
		columnMapping.put("informantZipCode", 313 + val);
		columnMapping.put("dateOfNotifyToDirector", 314 + val);
		columnMapping.put("timeOfNotifyToDirectory", 315 + val);
		columnMapping.put("facilityLicenseNumber", 316 + val);
		columnMapping.put("directorID", 317 + val);
		columnMapping.put("embalmerID", 318 + val);
		columnMapping.put("facilityName", 319 + val);
		columnMapping.put("facilityStreet", 320 + val);
		columnMapping.put("facilityCity", 321 + val);
		columnMapping.put("facilityState", 322 + val);
		columnMapping.put("facilityZipCode", 323 + val);
		columnMapping.put("facilityPhone", 324 + val);
		columnMapping.put("disposition", 325 + val);
		columnMapping.put("dispositionPlace", 326 + val);
		columnMapping.put("dispositionPlaceType", 327 + val);
		columnMapping.put("dispositionStreet", 328 + val);
		columnMapping.put("dispositionCity", 329 + val);
		columnMapping.put("dispositionState", 330 + val);
		columnMapping.put("dispositionCounty", 331 + val);
		columnMapping.put("dispositionZipCode", 332 + val);
		columnMapping.put("dateEmbalmed", 333 + val);
		columnMapping.put("dateOfDisposition", 334 + val);
		columnMapping.put("authorizingCoroner", 335 + val);
		columnMapping.put("notificationOfExaminerRequired", 336 + val);
		columnMapping.put("medicalExaminerBox1", 337 + val);
		columnMapping.put("certifierDateSigned", 338 + val);
		columnMapping.put("medicalExaminerBox2", 339 + val);
		columnMapping.put("medicalExaminerDateSigned", 340 + val);
		columnMapping.put("completedCauseOfDeathDoctorLicense", 341 + val);
		columnMapping.put("npCheckBox1", 342 + val);
		columnMapping.put("npDateSigned", 343 + val);
		columnMapping.put("npLicenseNumber", 344 + val);
		columnMapping.put("timeOfDeath", 345 + val);
		columnMapping.put("medicalExaminerDeathDate", 346 + val);
		columnMapping.put("timeOfDeath2", 347 + val);
		columnMapping.put("referredToMedicalExaminer", 348 + val);
		columnMapping.put("actualPlaceDeath", 349 + val);
		columnMapping.put("inpatient", 350 + val);
		columnMapping.put("medicalExaminerCaseNumber", 351 + val);
		columnMapping.put("attendingPhysician", 352 + val);
		columnMapping.put("completedCauseOfDeathDoctorName", 353 + val);
		columnMapping.put("completedCauseOfDeathDoctorStreet", 354 + val);
		columnMapping.put("completedCauseOfDeathDoctorCity", 355 + val);
		columnMapping.put("completedCauseOfDeathDoctorState", 356 + val);
		columnMapping.put("completedCauseOfDeathDoctorZip", 357 + val);
		columnMapping.put("completedCauseOfDeathDoctorPhone", 358 + val);
		columnMapping.put("physicianMD", 359 + val);
		columnMapping.put("physicianME", 360 + val);
		columnMapping.put("physicianDO", 361 + val);
		columnMapping.put("physicianHO", 362 + val);
		columnMapping.put("physDateFrom", 363 + val);
		columnMapping.put("physDateTo", 364 + val);
		columnMapping.put("physDateLast", 365 + val);
		columnMapping.put("physViewedYesNo", 366 + val);
		columnMapping.put("registrarFileDate", 367 + val);
		columnMapping.put("cause1", 368 + val);
		columnMapping.put("interval1", 369 + val);
		columnMapping.put("cause2", 370 + val);
		columnMapping.put("interval2", 371 + val);
		columnMapping.put("cause3", 372 + val);
		columnMapping.put("interval3", 373 + val);
		columnMapping.put("cause4", 374 + val);
		columnMapping.put("interval4", 375 + val);
		columnMapping.put("tobaccoUser", 376 + val);
		columnMapping.put("pregnantAtDeath", 377 + val);
		columnMapping.put("otherCondition", 378 + val);
		columnMapping.put("medicalExaminerAccidentSuicide", 379 + val);
		columnMapping.put("bodyFoundMore24Hr", 380 + val);
		columnMapping.put("autopsy", 381 + val);
		columnMapping.put("findings", 382 + val);
		columnMapping.put("hospiceStatus", 383 + val);
		columnMapping.put("medicalExaminerInjuryDate", 384 + val);
		columnMapping.put("medicalExaminerInjuryTime", 385 + val);
		columnMapping.put("medicalExaminerInjuryDescription", 386 + val);
		columnMapping.put("medicalExaminerInjuryAtWork", 387 + val);
		columnMapping.put("medicalExaminerInjuryPlace", 388 + val);
		columnMapping.put("medicalExaminerInjuryTransportation", 389 + val);
		columnMapping.put("medicalExaminerInjuryStreet", 390 + val);
		columnMapping.put("medicalExaminerInjuryCity", 391 + val);
		columnMapping.put("medicalExaminerInjuryState", 392 + val);

		columnMapping.put("timeOfService", 394 + val);
		columnMapping.put("dateOfService", 395 + val);
		columnMapping.put("dayOfService", 396 + val);
		columnMapping.put("addnlService", 397 + val);
		columnMapping.put("addnlTimeOfService", 398 + val);
		columnMapping.put("addnlDateOfService", 399 + val);
		columnMapping.put("addnlDayOfService", 400 + val);
		columnMapping.put("placeOfService", 401 + val);
		columnMapping.put("streetOfService", 402 + val);
		columnMapping.put("cityOfService", 403 + val);
		columnMapping.put("stateOfService", 404 + val);
		columnMapping.put("phoneOfService", 405 + val);
		columnMapping.put("addnlPlaceOfService", 406 + val);
		columnMapping.put("addnlStreetOfService", 407 + val);
		columnMapping.put("addnlCityOfService", 408 + val);
		columnMapping.put("addnlStateOfService", 409 + val);
		columnMapping.put("addnlPhoneOfService", 410 + val);
		columnMapping.put("cemeteryName", 411 + val);
		columnMapping.put("cemeteryStreet", 412 + val);
		columnMapping.put("cemeteryCity", 413 + val);
		columnMapping.put("cemeteryState", 414 + val);
		columnMapping.put("cemeteryZipCode", 415 + val);
		columnMapping.put("cemeteryCounty", 416 + val);
		columnMapping.put("cemeteryPhone", 417 + val);
		columnMapping.put("cemeteryVault", 418 + val);
		columnMapping.put("cemeterySection", 419 + val);
		columnMapping.put("cemeteryBlockNumber", 420 + val);
		columnMapping.put("cemeteryLot", 421 + val);
		columnMapping.put("cemeteryGraveNumber", 422 + val);
		columnMapping.put("cemeteryTent", 423 + val);
		columnMapping.put("cemeterySetAndSeal", 424 + val);
		columnMapping.put("cemeteryOpen", 425 + val);
		columnMapping.put("cemeteryTime", 426 + val);
		columnMapping.put("cemeteryDisposition", 427 + val);
		columnMapping.put("cremationDateOfService", 428 + val);
		columnMapping.put("crematoryName", 429 + val);
		columnMapping.put("crematoryStreet", 430 + val);
		columnMapping.put("crematoryCity", 431 + val);
		columnMapping.put("crematoryState", 432 + val);
		columnMapping.put("crematoryCounty", 433 + val);
		columnMapping.put("crematoryZip", 434 + val);
		columnMapping.put("cemeteryStaffAndAuto", 435 + val);
		columnMapping.put("donations", 436 + val);
		columnMapping.put("specialInstructions", 437 + val);
		columnMapping.put("cardsNumber", 438 + val);
		columnMapping.put("cardsStyle", 439 + val);
		columnMapping.put("churchName", 440 + val);
		columnMapping.put("churchAddress", 441 + val);
		columnMapping.put("churchAddress2", 442 + val);
		columnMapping.put("churchPhone", 443 + val);
		columnMapping.put("minister1", 444 + val);
		columnMapping.put("minister1Email", 445 + val);
		columnMapping.put("minister2", 446 + val);
		columnMapping.put("minister2Email", 447 + val);
		columnMapping.put("organist", 448 + val);
		columnMapping.put("soloist", 449 + val);
		columnMapping.put("jewelry", 450 + val);
		columnMapping.put("songs", 451 + val);
		columnMapping.put("hairStyle", 452 + val);
		columnMapping.put("restoration", 453 + val);
		columnMapping.put("flowerArrangementsDescription", 454 + val);
		columnMapping.put("flowerSupplierAddressAndPhone", 455 + val);
		columnMapping.put("flowerDelivery", 456 + val);
		columnMapping.put("flowerPickup", 457 + val);
		columnMapping.put("visitationInformation", 458 + val);
		columnMapping.put("pickupFamilyAt", 459 + val);
		columnMapping.put("pickupFamilyTime", 460 + val);
		columnMapping.put("certifiedCopies", 461 + val);
		columnMapping.put("certifiedSendTo", 462 + val);
		columnMapping.put("specialServices", 463 + val);
		columnMapping.put("memorialsNumber", 464 + val);
		columnMapping.put("memorialStyle", 465 + val);

		columnMapping.put("pallBearer1Name", 480 + val);
		columnMapping.put("pallBearer1Street", 481 + val);
		columnMapping.put("pallBearer1CityStateZip", 482 + val);				
		columnMapping.put("pallBearer2Name", 483 + val);
		columnMapping.put("pallBearer2Street", 484 + val);
		columnMapping.put("pallBearer2CityStateZip", 485 + val);
		columnMapping.put("pallBearer3Name", 486 + val);
		columnMapping.put("pallBearer3Street", 487 + val);
		columnMapping.put("pallBearer3CityStateZip", 488 + val);
		columnMapping.put("pallBearer4Name", 489 + val);
		columnMapping.put("pallBearer4Street", 490 + val);
		columnMapping.put("pallBearer4CityStateZip", 491 + val);
		columnMapping.put("pallBearer5Name", 492 + val);
		columnMapping.put("pallBearer5Street", 493 + val);
		columnMapping.put("pallBearer5CityStateZip", 494 + val);
		columnMapping.put("pallBearer6Name", 495 + val);
		columnMapping.put("pallBearer6Street", 496 + val);
		columnMapping.put("pallBearer6CityStateZip", 497 + val);
		columnMapping.put("pallBearer7Name", 498 + val);
		columnMapping.put("pallBearer7Street", 499 + val);
		columnMapping.put("pallBearer7CityStateZip", 500 + val);
		columnMapping.put("pallBearer8Name", 501 + val);
		columnMapping.put("pallBearer8Street", 502 + val);
		columnMapping.put("pallBearer8CityStateZip", 503 + val);
		columnMapping.put("honoraryPallBearer1Name", 504 + val);
		columnMapping.put("honoraryPallBearer1Street", 505 + val);
		columnMapping.put("honoraryPallBearer1CityStateZip", 506 + val);
		columnMapping.put("honoraryPallBearer2Name", 507 + val);
		columnMapping.put("honoraryPallBearer2Street", 508 + val);
		columnMapping.put("honoraryPallBearer2CityStateZip", 509 + val);
		columnMapping.put("honoraryPallBearer3Name", 510 + val);
		columnMapping.put("honoraryPallBearer3Street", 511 + val);
		columnMapping.put("honoraryPallBearer3CityStateZip", 512 + val);
		columnMapping.put("honoraryPallBearer4Name", 513 + val);
		columnMapping.put("honoraryPallBearer4Street", 514 + val);
		columnMapping.put("honoraryPallBearer4CityStateZip", 515 + val);
		columnMapping.put("honoraryPallBearer5Name", 516 + val);
		columnMapping.put("honoraryPallBearer5Street", 517 + val);
		columnMapping.put("honoraryPallBearer5CityStateZip", 518 + val);
		columnMapping.put("honoraryPallBearer6Name", 519 + val);
		columnMapping.put("honoraryPallBearer6Street", 520 + val);
		columnMapping.put("honoraryPallBearer6CityStateZip", 521 + val);
		columnMapping.put("honoraryPallBearer7Name", 522 + val);
		columnMapping.put("honoraryPallBearer7Street", 523 + val);
		columnMapping.put("honoraryPallBearer7CityStateZip", 524 + val);
		columnMapping.put("honoraryPallBearer8Name", 525 + val);
		columnMapping.put("honoraryPallBearer8Street", 526 + val);
		columnMapping.put("honoraryPallBearer8CityStateZip", 527 + val);

		columnMapping.put("vetName", 816 + val);
		columnMapping.put("vetOtherName", 817 + val);
		columnMapping.put("armyBox", 818 + val);
		columnMapping.put("navyBox", 819 + val);
		columnMapping.put("airForceBox", 820 + val);
		columnMapping.put("marineBox", 821 + val);
		columnMapping.put("coastGuardBox", 822 + val);
		columnMapping.put("selReserveBox", 823 + val);
		columnMapping.put("otherBranchBox", 824 + val);
		columnMapping.put("otherBranchOfService", 824 + val);
		columnMapping.put("spanAmerBox", 825 + val);
		columnMapping.put("wwiiBox", 826 + val);
		columnMapping.put("after55Box", 827 + val);
		columnMapping.put("gulfBox", 828 + val);
		columnMapping.put("wwiBox", 829 + val);
		columnMapping.put("koreanBox", 830 + val);
		columnMapping.put("vietnamBox", 831 + val);
		columnMapping.put("otherServBox", 832 + val);
		columnMapping.put("otherVetService", 832 + val);
		columnMapping.put("condition1Box", 833 + val);
		columnMapping.put("condition2Box", 834 + val);
		columnMapping.put("condition3Box", 835 + val);
		columnMapping.put("condition4Box", 836 + val);
		columnMapping.put("condition5Box", 837 + val);
		columnMapping.put("personReceive", 838 + val);
		columnMapping.put("receivAddress1", 839 + val);
		columnMapping.put("receivAddress2", 840 + val);
		columnMapping.put("receivRelation", 841 + val);
		columnMapping.put("vaFileNumber", 842 + val);
		columnMapping.put("socSecNumber", 843 + val);
		columnMapping.put("serialNumber", 844 + val);
		columnMapping.put("enlistmentDate", 845 + val);
		columnMapping.put("dischargeDate", 846 + val);
		columnMapping.put("birthDate", 847 + val);
		columnMapping.put("deathDate", 848 + val);
		columnMapping.put("burialDate", 849 + val);
		columnMapping.put("burialPlace", 850 + val);
		columnMapping.put("burialStreet", 851 + val);
		columnMapping.put("burialCity", 852 + val);
		columnMapping.put("burialState", 853 + val);
		columnMapping.put("burialZipCode", 854 + val);
		columnMapping.put("docShowEligibility", 855 + val);
		columnMapping.put("remarks", 856 + val);
		columnMapping.put("appAddress1", 857 + val);
		columnMapping.put("appAddress2", 858 + val);
		columnMapping.put("appRelation", 859 + val);
		columnMapping.put("appDate", 860 + val);

		columnMapping.put("ben1VetFirstName", 862 + val);
		columnMapping.put("ben1VetMiddleName", 863 + val);
		columnMapping.put("ben1VetLastName", 864 + val);
		columnMapping.put("ben1SSN", 865 + val);
		columnMapping.put("ben1FileNumber", 866 + val);				
		columnMapping.put("ben1ClaimantName", 867 + val);
		columnMapping.put("ben1ClaimantStreet", 868 + val);
		columnMapping.put("ben1ClaimCityStZip", 869 + val);
		columnMapping.put("ben1DayPhone", 870 + val);
		columnMapping.put("ben1NightPhone", 871 + val);
		columnMapping.put("ben1BirthDate", 872 + val);
		columnMapping.put("ben1DeathDate", 873 + val);
		columnMapping.put("ben1BurialDate", 874 + val);
		columnMapping.put("ben1PlaceBirth", 875 + val);
		columnMapping.put("ben1PlaceDeath", 876 + val);
		columnMapping.put("ben1DateEntered1", 877 + val);
		columnMapping.put("ben1PlaceEntered1", 878 + val);
		columnMapping.put("ben1SepSrvcDate1", 879 + val);
		columnMapping.put("ben1SepSrvcPlace1", 880 + val);
		columnMapping.put("ben1ServiceNumber1", 881 + val);
		columnMapping.put("ben1GradeRank1", 882 + val);
		columnMapping.put("ben1DateEntered2", 883 + val);
		columnMapping.put("ben1PlaceEntered2", 884 + val);
		columnMapping.put("ben1SepSrvcDate2", 885 + val);
		columnMapping.put("ben1SepSrvcPlace2", 886 + val);
		columnMapping.put("ben1ServiceNumber2", 887 + val);
		columnMapping.put("ben1GradeRank2", 888 + val);
		columnMapping.put("ben1DateEntered3", 889 + val);
		columnMapping.put("ben1PlaceEntered3", 890 + val);
		columnMapping.put("ben1SepSrvcDate3", 891 + val);
		columnMapping.put("ben1SepSrvcPlace3", 892 + val);
		columnMapping.put("ben1ServiceNumber3", 893 + val);
		columnMapping.put("ben1GradeRank3", 894 + val);
		columnMapping.put("ben1Box8OtherName", 895 + val);
		columnMapping.put("ben1Box9", 896 + val);
		columnMapping.put("ben1BurialPlace", 897 + val);
		columnMapping.put("ben1Box11", 898 + val);
		columnMapping.put("ben1Box12", 899 + val);
		columnMapping.put("ben1Box13", 900 + val);
		columnMapping.put("ben1Box14NameAddr", 901 + val);
		columnMapping.put("ben1Box15TotBurExp", 902 + val);
		columnMapping.put("ben1Box16AmtPaid", 903 + val);
		columnMapping.put("ben1Box17WhoseFund", 904 + val);
		columnMapping.put("ben1Box18", 905 + val);
		columnMapping.put("ben1Box18bAmtReimb", 906 + val);
		columnMapping.put("ben1Box18cSrcReimb", 907 + val);
		columnMapping.put("ben1Box19", 908 + val);
		columnMapping.put("ben1Box19bAmount", 909 + val);
		columnMapping.put("ben1Box19cSource", 910 + val);
		columnMapping.put("ben1Box20", 911 + val);
		columnMapping.put("ben2Box21", 912 + val);
		columnMapping.put("ben2Box22Place1", 913 + val);
		columnMapping.put("ben2Box22Place2", 914 + val);
		columnMapping.put("ben2Box23aCost", 915 + val);
		columnMapping.put("ben2Box23bDatePurc", 916 + val);
		columnMapping.put("ben2Box23cDatePay", 917 + val);
		columnMapping.put("ben2Box24", 918 + val);
		columnMapping.put("ben2Box24bAmtPaid", 919 + val);
		columnMapping.put("ben2Box25WhoseFund", 920 + val);
		columnMapping.put("ben2Box26", 921 + val);
		columnMapping.put("ben2Box26bAmount", 922 + val);
		columnMapping.put("ben2Box26cSource", 923 + val);
		columnMapping.put("ben2Box27", 924 + val);
		columnMapping.put("ben2Box27bAmount", 925 + val);
		columnMapping.put("ben2Box27cSource", 926 + val);
		columnMapping.put("ben2Box28bOfficPos", 927 + val);
		columnMapping.put("ben2Box29Agency", 928 + val);
		columnMapping.put("ben2Box30bName", 929 + val);
		columnMapping.put("ben2Box31Address", 930 + val);
		columnMapping.put("ben2Box32Date", 931 + val);
		columnMapping.put("ben2Box33Relation", 932 + val);

		columnMapping.put("headRequestType", 933 + val);				
		columnMapping.put("headFirstName", 934 + val);
		columnMapping.put("headMiddleName", 935 + val);
		columnMapping.put("headLastName", 936 + val);
		columnMapping.put("headSuffix", 937 + val);
		columnMapping.put("ssn", 938 + val);
		columnMapping.put("serialNumber", 939 + val);
		columnMapping.put("birthMonth", 940 + val);
		columnMapping.put("birthDay", 941 + val);
		columnMapping.put("birthYear", 942 + val);
		columnMapping.put("deathMonth", 943 + val);
		columnMapping.put("deathDay", 944 + val);
		columnMapping.put("deathYear", 945 + val);
		columnMapping.put("headBox2", 946 + val);
		columnMapping.put("enteredMonth1", 947 + val);
		columnMapping.put("enteredDay1", 948 + val);
		columnMapping.put("enteredYear1", 949 + val);
		columnMapping.put("enteredMonth2", 950 + val);
		columnMapping.put("enteredDay2", 951 + val);
		columnMapping.put("enteredYear2", 952 + val);
		columnMapping.put("separatedMonth1", 953 + val);
		columnMapping.put("separatedDay1", 954 + val);
		columnMapping.put("separatedYear1", 955 + val);
		columnMapping.put("separatedMonth2", 956 + val);
		columnMapping.put("separatedDay2", 957 + val);
		columnMapping.put("separatedYear2", 958 + val);
		columnMapping.put("headBranchArmy", 959 + val);
		columnMapping.put("headBranchNavy", 960 + val);
		columnMapping.put("headBranchMarines", 961 + val);
		columnMapping.put("headBranchCoastGua", 962 + val);
		columnMapping.put("headBranchAirForce", 963 + val);
		columnMapping.put("headBranchArmyAir", 964 + val);
		columnMapping.put("headBranchMerchantMarines", 965 + val);
		columnMapping.put("headBranchSpecify", 966 + val);
		columnMapping.put("headBranchOther", 967 + val);
		columnMapping.put("headHighestRank", 967 + val);
		columnMapping.put("headWarWWII", 968 + val);
		columnMapping.put("headWarKorean", 969 + val);
		columnMapping.put("headWarVietnam", 970 + val);
		columnMapping.put("headWarPersianGulf", 971 + val);
		columnMapping.put("headWarSpecify", 972 + val);
		columnMapping.put("headWarOther", 972 + val);
		columnMapping.put("headValorMOH", 973 + val);
		columnMapping.put("headValorDSC", 974 + val);
		columnMapping.put("headValorNC", 975 + val);
		columnMapping.put("headValorAFC", 976 + val);
		columnMapping.put("headValorSS", 977 + val);
		columnMapping.put("headValorBSM", 978 + val);
		columnMapping.put("headValorPH", 979 + val);
		columnMapping.put("headValorOther", 980 + val);
		columnMapping.put("headValorOtherSpecify", 980 + val);
		columnMapping.put("stoneType", 981 + val);
		columnMapping.put("headBeliefNone", 982 + val);
		columnMapping.put("headBeliefChrist", 983 + val);
		columnMapping.put("headBeliefBuddhist", 984 + val);
		columnMapping.put("headBeliefJewish", 985 + val);
		columnMapping.put("headBeliefOther", 986 + val);
		columnMapping.put("headBeliefSpecify", 986 + val);
		columnMapping.put("headAppNameAddress", 987 + val);
		columnMapping.put("headAppPhoneNumber", 988 + val);
		columnMapping.put("headAppEmail", 989 + val);
		columnMapping.put("headAppFax", 990 + val);
		columnMapping.put("headRelationship", 991 + val);
		columnMapping.put("headRelOtherSpecify", 992 + val);
		columnMapping.put("headRelOther", 992 + val);
		columnMapping.put("headConsignNameAddr", 993 + val);
		columnMapping.put("headCemeteryPhone", 994 + val);
		columnMapping.put("headCemNameAddress", 995 + val);
		columnMapping.put("headGraveID", 996 + val);
		columnMapping.put("headGraveSection", 997 + val);
		columnMapping.put("headGraveNumber", 998 + val);
		columnMapping.put("headGraveMarkedType", 999 + val);
		columnMapping.put("headRemarks", 1000 + val);
		columnMapping.put("appDate", 1001 + val);

		//columnMapping.put("issueDate", 392);
	}
	
	public static ColumnMapping getInstance(int val) {
		if(instance == null)
			instance = new ColumnMapping(val);
		
		return instance;
	}
	
	public Map<String, Integer> getColumnMapping() {
		return columnMapping;
	}
	
	public Map<String, Integer> getPreNeedColumnMapping() {
		return preNeedColumnMapping;
	}
}
