/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 * CJongs
 */
package fdms.ui.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-17-2007
 * 
 * XDoclet definition:
 * @struts.form name="mainForm"
 */
public class MovingCaseForm extends ActionForm {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7570959813472847388L;

	private String userLocationId;

	private String userLocaleId;

	private boolean showLocationList = false;
	
	private String directionType;
	private String operate;
	
	private int vitalsId;
	
	private String firstname;
	private String lastname;
	private String director;
	private String chapelname;
	private String facility;
	private String origDirector;
	private String origFacility;
	private boolean facilitySame;
	private String facilityName;
	private String facilityStreet;
	private String facilityCity;
	private String facilityState;
	private String facilityZip;
	private String facilityPhone;
	private String facilityLicense;

	private String chapelName;
	private String chapelStreet;
	private String chapelCity;
	private String chapelState;
	private String chapelZip;
	private String chapelPhone;
	private String chapelLicense;
	
	private String message;
	private String haveMessage;

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		this.setFacilitySame(false);
	}

	public String getUserLocationId() {
		return userLocationId;
	}

	public void setUserLocationId(String userLocationId) {
		this.userLocationId = userLocationId;
	}

	public String getUserLocaleId() {
		return userLocaleId;
	}

	public void setUserLocaleId(String userLocaleId) {
		this.userLocaleId = userLocaleId;
	}

	public boolean isShowLocationList() {
		return showLocationList;
	}

	public void setShowLocationList(boolean showLocationList) {
		this.showLocationList = showLocationList;
	}

	public int getVitalsId() {
		return vitalsId;
	}

	public void setVitalsId(int vitalsId) {
		this.vitalsId = vitalsId;
	}

	public String getFirstname() {
		return firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getDirector() {
		return director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	public String getChapelname() {
		return chapelname;
	}

	public void setChapelname(String chapelname) {
		this.chapelname = chapelname;
	}

	public String getDirectionType() {
		return directionType;
	}

	public void setDirectionType(String directionType) {
		this.directionType = directionType;
	}

	public String getOperate() {
		return operate;
	}

	public void setOperate(String operate) {
		this.operate = operate;
	}

	public String getFacility() {
		return facility;
	}

	public void setFacility(String facility) {
		this.facility = facility;
	}

	public String getOrigDirector() {
		return origDirector;
	}

	public void setOrigDirector(String origDirector) {
		this.origDirector = origDirector;
	}

	public String getOrigFacility() {
		return origFacility;
	}

	public void setOrigFacility(String origFacility) {
		this.origFacility = origFacility;
	}

	public boolean isFacilitySame() {
		return facilitySame;
	}

	public void setFacilitySame(boolean facilitySame) {
		this.facilitySame = facilitySame;
	}

	public String getFacilityName() {
		return facilityName;
	}

	public void setFacilityName(String facilityName) {
		this.facilityName = facilityName;
	}

	public String getFacilityStreet() {
		return facilityStreet;
	}

	public void setFacilityStreet(String facilityStreet) {
		this.facilityStreet = facilityStreet;
	}

	public String getFacilityCity() {
		return facilityCity;
	}

	public void setFacilityCity(String facilityCity) {
		this.facilityCity = facilityCity;
	}

	public String getFacilityState() {
		return facilityState;
	}

	public void setFacilityState(String facilityState) {
		this.facilityState = facilityState;
	}

	public String getFacilityZip() {
		return facilityZip;
	}

	public void setFacilityZip(String facilityZip) {
		this.facilityZip = facilityZip;
	}

	public String getFacilityPhone() {
		return facilityPhone;
	}

	public void setFacilityPhone(String facilityPhone) {
		this.facilityPhone = facilityPhone;
	}

	public String getFacilityLicense() {
		return facilityLicense;
	}

	public void setFacilityLicense(String facilityLicense) {
		this.facilityLicense = facilityLicense;
	}

	public String getChapelName() {
		return chapelName;
	}

	public void setChapelName(String chapelName) {
		this.chapelName = chapelName;
	}

	public String getChapelStreet() {
		return chapelStreet;
	}

	public void setChapelStreet(String chapelStreet) {
		this.chapelStreet = chapelStreet;
	}

	public String getChapelCity() {
		return chapelCity;
	}

	public void setChapelCity(String chapelCity) {
		this.chapelCity = chapelCity;
	}

	public String getChapelState() {
		return chapelState;
	}

	public void setChapelState(String chapelState) {
		this.chapelState = chapelState;
	}

	public String getChapelZip() {
		return chapelZip;
	}

	public void setChapelZip(String chapelZip) {
		this.chapelZip = chapelZip;
	}

	public String getChapelPhone() {
		return chapelPhone;
	}

	public void setChapelPhone(String chapelPhone) {
		this.chapelPhone = chapelPhone;
	}

	public String getChapelLicense() {
		return chapelLicense;
	}

	public void setChapelLicense(String chapelLicense) {
		this.chapelLicense = chapelLicense;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getHaveMessage() {
		return haveMessage;
	}

	public void setHaveMessage(String haveMessage) {
		this.haveMessage = haveMessage;
	}
	

}