/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.aldorsolutions.dashboard.struts.form.acct;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-25-2007
 * 
 * XDoclet definition:
 * @struts.form name="acctListVendorsForm"
 */
public class AcctListVendorsForm extends ActionForm {
	/*
	 * Generated Methods
	 */

	ArrayList vendors = new ArrayList();
	
	String searchVendorName;

	/**
	 * @return the searchVendorName
	 */
	public String getSearchVendorName() {
		return searchVendorName;
	}

	/**
	 * @param searchVendorName the searchVendorName to set
	 */
	public void setSearchVendorName(String searchVendorName) {
		this.searchVendorName = searchVendorName;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * @return the vendors
	 */
	public ArrayList getVendors() {
		return vendors;
	}

	/**
	 * @param vendors the vendors to set
	 */
	public void setVendors(ArrayList vendors) {
		this.vendors = vendors;
	}
	
	
}