/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.aldorsolutions.dashboard.struts.form.users;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-27-2007
 * 
 * XDoclet definition:
 * @struts.form name="userListingForm"
 */
public class UserListingForm extends ActionForm {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -4832490451951455248L;
	
	long userID;
	String userName;
	String firstName;
	String lastName;
	String emailAddress;
	boolean userLimitOverride;
	String extLimit;
	String intLimit;
	
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * @return the emailAddress
	 */
	public String getEmailAddress() {
		return emailAddress;
	}

	/**
	 * @return the extLimit
	 */
	public String getExtLimit() {
		return extLimit;
	}

	/**
	 * @return the firstName
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * @return the intLimit
	 */
	public String getIntLimit() {
		return intLimit;
	}

	/**
	 * @return the lastName
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * @return the userID
	 */
	public long getUserID() {
		return userID;
	}

	/**
	 * @return the userName
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * @param emailAddress the emailAddress to set
	 */
	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	/**
	 * @param extLimit the extLimit to set
	 */
	public void setExtLimit(String extLimit) {
		this.extLimit = extLimit;
	}

	/**
	 * @param firstName the firstName to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * @param intLimit the intLimit to set
	 */
	public void setIntLimit(String intLimit) {
		this.intLimit = intLimit;
	}

	/**
	 * @param lastName the lastName to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * @param userID the userID to set
	 */
	public void setUserID(long userID) {
		this.userID = userID;
	}

	/**
	 * @param userName the userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * @return the userLimitOverride
	 */
	public boolean isUserLimitOverride() {
		return userLimitOverride;
	}

	/**
	 * @param userLimitOverride the userLimitOverride to set
	 */
	public void setUserLimitOverride(boolean userLimitOverride) {
		this.userLimitOverride = userLimitOverride;
	}
	
}