/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.aldorsolutions.dashboard.struts.form.users;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import com.aldorassist.webfdms.model.LocationDTO;
import com.aldorsolutions.webfdms.admin.user.model.UserDTO;
import com.aldorsolutions.webfdms.ums.model.RolesDTO;

/**
 * MyEclipse Struts Creation date: 04-30-2007
 * 
 * XDoclet definition:
 * 
 * @struts.form name="userEditForm"
 */
public class UserEditForm extends ActionForm {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3800176979064378129L;
	
	private long userID = 0;
	private long companyID = 0;
	private String userName = null;
	private String password = null;
	private String firstName = null;
	private String lastName = null;
	private String initials = null;
	private String companyName = null;
	private String email = null;
	private boolean vacationFlag;
	private long vacationUserID = 0;
	private boolean userLimitOverride = false;
	private String externalVendorLimit = "$0.00";
	private String internalVendorLimit = "$0.00";
	private ArrayList <UserDTO>  acctUsers = new ArrayList <UserDTO> ();
	private ArrayList <RolesDTO> assignedRoles = new ArrayList <RolesDTO> ();
	private ArrayList <RolesDTO> availableRoles = new ArrayList <RolesDTO> ();
	private ArrayList <LocationDTO> acctLocations = new ArrayList <LocationDTO> ();
	private String submitButton = null;
	
	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * @return the acctLocations
	 */
	public ArrayList <LocationDTO> getAcctLocations() {
		return acctLocations;
	}

	/**
	 * @return the acctUsers
	 */
	public ArrayList <UserDTO> getAcctUsers() {
		return acctUsers;
	}

	/**
	 * @return the assignedRoles
	 */
	public ArrayList <RolesDTO> getAssignedRoles() {
		return assignedRoles;
	}

	/**
	 * @return the companyID
	 */
	public long getCompanyID() {
		return companyID;
	}

	/**
	 * @return the companyName
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * @return the firstName
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * @return the initials
	 */
	public String getInitials() {
		return initials;
	}

	/**
	 * @return the lastName
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * @return the userID
	 */
	public long getUserID() {
		return userID;
	}

	/**
	 * @return the userName
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * @return the vacationFlag
	 */
	public boolean isVacationFlag() {
		return vacationFlag;
	}

	/**
	 * @return the vacationUserID
	 */
	public long getVacationUserID() {
		return vacationUserID;
	}

	/**
	 * @param acctLocations the acctLocations to set
	 */
	public void setAcctLocations(ArrayList <LocationDTO> acctLocations) {
		this.acctLocations = acctLocations;
	}

	/**
	 * @param acctUsers the acctUsers to set
	 */
	public void setAcctUsers(ArrayList <UserDTO> acctUsers) {
		this.acctUsers = acctUsers;
	}

	/**
	 * @param assignedRoles the assignedRoles to set
	 */
	public void setAssignedRoles(ArrayList <RolesDTO> assignedRoles) {
		this.assignedRoles = assignedRoles;
	}

	/**
	 * @param companyID the companyID to set
	 */
	public void setCompanyID(long companyID) {
		this.companyID = companyID;
	}

	/**
	 * @param companyName the companyName to set
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @param firstName the firstName to set
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * @param initials the initials to set
	 */
	public void setInitials(String initials) {
		this.initials = initials;
	}

	/**
	 * @param lastName the lastName to set
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	/**
	 * @param userID the userID to set
	 */
	public void setUserID(long userID) {
		this.userID = userID;
	}

	/**
	 * @param userName the userName to set
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * @param vacationFlag the vacationFlag to set
	 */
	public void setVacationFlag(boolean vacationFlag) {
		this.vacationFlag = vacationFlag;
	}

	/**
	 * @param vacationUserID the vacationUserID to set
	 */
	public void setVacationUserID(long vacationUserID) {
		this.vacationUserID = vacationUserID;
	}

	/**
	 * @return the availableRoles
	 */
	public ArrayList <RolesDTO> getAvailableRoles() {
		return availableRoles;
	}

	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * @param availableRoles the availableRoles to set
	 */
	public void setAvailableRoles(ArrayList <RolesDTO> availableRoles) {
		this.availableRoles = availableRoles;
	}

	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * @return the userLimitOverride
	 */
	public boolean isUserLimitOverride() {
		return userLimitOverride;
	}

	/**
	 * @param userLimitOverride the userLimitOverride to set
	 */
	public void setUserLimitOverride(boolean userLimitOverride) {
		this.userLimitOverride = userLimitOverride;
	}

	/**
	 * @return the externalVendorLimit
	 */
	public String getExternalVendorLimit() {
		return externalVendorLimit;
	}

	/**
	 * @return the internalVendorLimit
	 */
	public String getInternalVendorLimit() {
		return internalVendorLimit;
	}

	/**
	 * @param externalVendorLimit the externalVendorLimit to set
	 */
	public void setExternalVendorLimit(String externalVendorLimit) {
		this.externalVendorLimit = externalVendorLimit;
	}

	/**
	 * @param internalVendorLimit the internalVendorLimit to set
	 */
	public void setInternalVendorLimit(String internalVendorLimit) {
		this.internalVendorLimit = internalVendorLimit;
	}

	/**
	 * @return the submitButton
	 */
	public String getSubmitButton() {
		return submitButton;
	}

	/**
	 * @param submitButton the submitButton to set
	 */
	public void setSubmitButton(String submitButton) {
		this.submitButton = submitButton;
	}
	
}