/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.aldorsolutions.dashboard.struts.action.acct;

import java.util.ArrayList;

import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.log4j.Logger;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.aldorassist.webfdms.dao.InvoiceDAO;
import com.aldorassist.webfdms.delegate.InvoiceManager;
import com.aldorassist.webfdms.model.InvoiceDTO;
import com.aldorsolutions.dashboard.struts.form.acct.InvoiceConfirmPaymentForm;
import com.aldorsolutions.webfdms.beans.DbUserSession;
import com.aldorsolutions.webfdms.beans.display.InvoiceConfirmPaymentBean;
import com.aldorsolutions.webfdms.util.SessionValueKeys;

/** 
 * MyEclipse Struts
 * Creation date: 09-24-2007
 * 
 * XDoclet definition:
 * @struts.action path="/invoiceConfirmPayment" name="invoiceConfirmPaymentForm" input="/acct/invoiceConfirmPayment.jsp" scope="request" validate="true"
 */
public class InvoiceConfirmPaymentSubmitAction extends Action {
	
	private Logger logger = Logger.getLogger(InvoiceConfirmPaymentSubmitAction.class.getName());

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		InvoiceConfirmPaymentForm invoiceConfirmPaymentForm = (InvoiceConfirmPaymentForm) form;
		
		String submit = invoiceConfirmPaymentForm.getSubmitButton();
		
		if ( submit.equals("Cancel") ) {
			return ( mapping.findForward("invoiceList") );
		}
		//ArrayList <InvoiceDTO> invoices = invoiceDao.getFilterInvoices(filterText, filterValue, filterValueDate, orderBy );
		ArrayList <InvoiceConfirmPaymentBean> invoices = invoiceConfirmPaymentForm.getInvoices();
		HttpSession session =  request.getSession();
        DbUserSession user = (DbUserSession) session.getAttribute(SessionValueKeys.DB_USER);
		ActionMessages errors = new ActionMessages();
		InvoiceDAO invoiceDAO = new InvoiceDAO(user);
		//ApMasterDAO apMasterDAO = new ApMasterDAO(user);
		InvoiceManager invMgr = new InvoiceManager();
		ServletContext context = this.getServlet().getServletContext();
		String [] selectedInvoices = new String[invoices.size()];
		
		ArrayList<String> checkURL = new ArrayList<String>(); 
		
		int i = 0;
	
		for ( InvoiceConfirmPaymentBean invoiceBean : invoices ) {
			
			try {
				InvoiceDTO invoice = invoiceDAO.getInvoice( invoiceBean.getInvoiceID() );
				
				//create the check and print it.
				errors.add( invMgr.confirmInvoicePayment(request, response, context, invoice) );
		
				
				//checkURL.add(session.getAttribute("checkWriterURL").toString());
				
				selectedInvoices[i++] = Integer.toString(invoice.getInvoiceID());
			} catch ( Exception e ) {
				logger.debug(e.getMessage(), e);
				errors.add(ActionMessages.GLOBAL_MESSAGE, new ActionMessage("error.exception", e.getMessage()) );
			}
		}
		
   		ArrayList <InvoiceDTO> confirmInvoices = new ArrayList <InvoiceDTO> ();
		confirmInvoices = invoiceDAO.getInvoices(selectedInvoices);	
		for ( InvoiceDTO confirmInvoice : confirmInvoices) {
			//confirmInvoice.setInvoiceStatus(InvoiceDTO.INVOICE_PRINT);
			confirmInvoice.setInvoiceStatus(InvoiceDTO.INVOICE_APPROVE);
			try {
				invoiceDAO.updateInvoice(confirmInvoice);
			}
			catch ( Exception e ) {
				
			}
		}						
		
		
		if ( errors.isEmpty() == false ) {
			saveErrors(request, errors);
		}
		session.setAttribute("checkWriterURL", "displayReport.jsp?reportURL=http://asreports.aldorsolutions.com/WebfdmsReporting/exported/cjongs/demo/demandcheck.6.0128045942.pdf");
		
		checkURL.add("displayReport.jsp?reportURL=http://asreports.aldorsolutions.com/WebfdmsReporting/exported/cjongs/demo/demandcheck.6.0128043553.pdf"); 
		checkURL.add("displayReport.jsp?reportURL=http://asreports.aldorsolutions.com/WebfdmsReporting/exported/cjongs/demo/demandcheck.6.0128043707.pdf");
		
		session.setAttribute("checkURL",checkURL );
		return ( mapping.findForward("invoiceList") );
	}
}