/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.aldorsolutions.dashboard.struts.form.acct;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-28-2007
 * 
 * XDoclet definition:
 * @struts.form name="vendorLocEditForm"
 */
public class VendorLocEditForm extends ActionForm {

	private long vendorLocationID;
	
	private String defaultAcct;
	
	private long vendorID;
	
	private long locationID;
	
	private long localeID;
	
	private String submitType;
	
	private String localeMapJavascript;
	
	/**
	 * @return the defaultAcct
	 */
	public String getDefaultAcct() {
		return defaultAcct;
	}

	/**
	 * @return the localeID
	 */
	public long getLocaleID() {
		return localeID;
	}

	/**
	 * @return the locationID
	 */
	public long getLocationID() {
		return locationID;
	}

	/**
	 * @return the vendorID
	 */
	public long getVendorID() {
		return vendorID;
	}

	/**
	 * @return the vendorLocationID
	 */
	public long getVendorLocationID() {
		return vendorLocationID;
	}

	/**
	 * @param defaultAcct the defaultAcct to set
	 */
	public void setDefaultAcct(String defaultAcct) {
		this.defaultAcct = defaultAcct;
	}

	/**
	 * @param localeID the localeID to set
	 */
	public void setLocaleID(long localeID) {
		this.localeID = localeID;
	}

	/**
	 * @param locationID the locationID to set
	 */
	public void setLocationID(long locationID) {
		this.locationID = locationID;
	}

	/**
	 * @param vendorID the vendorID to set
	 */
	public void setVendorID(long vendorID) {
		this.vendorID = vendorID;
	}

	/**
	 * @param vendorLocationID the vendorLocationID to set
	 */
	public void setVendorLocationID(long vendorLocationID) {
		this.vendorLocationID = vendorLocationID;
	}
	
	/**
	 * @return the submitType
	 */
	public String getSubmitType() {
		return submitType;
	}

	/**
	 * @param submitType the submitType to set
	 */
	public void setSubmitType(String submitType) {
		this.submitType = submitType;
	}
	
	/**
	 * @return the localeMapJavascript
	 */
	public String getLocaleMapJavascript() {
		return localeMapJavascript;
	}

	/**
	 * @param localeMapJavascript the localeMapJavascript to set
	 */
	public void setLocaleMapJavascript(String localeMapJavascript) {
		this.localeMapJavascript = localeMapJavascript;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}