/*
 * Generated by XDoclet - Do not edit!
 */
package com.aldorsolutions.webfdms.company.ejb;

/**
 * Local home interface for NewCompanySetUp.
 * @xdoclet-generated at ${TODAY}
 * @copyright The XDoclet Team
 * @author XDoclet
 * @version ${version}
 */
public interface NewCompanySetUpLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/NewCompanySetUpLocal";
   public static final String JNDI_NAME="NewCompanySetUpLocal";

   public com.aldorsolutions.webfdms.company.ejb.NewCompanySetUpLocal create()
      throws javax.ejb.CreateException;

}
