/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package fdms.ui.struts.form;

import java.util.ArrayList;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.util.LabelValueBean;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 06-25-2007, 030309
 * 
 * XDoclet definition:
 * @struts.form name="vendorEditForm"
 */
public class VendorEditForm extends ActionForm {

	private long vendorID;

	private long localeID;

	private long locationID;
	
	private String vendorCode;

	private String name;

	private String addr1;

	private String addr2;

	private String cityState;

	private String postalCode;

	private String contactName;

	private String phone;

	private String emailAddr;

	private String defaultAcct;

	private String notes;
	
	private String deleteCode;

	private String internalVendor;

	private String[] locationIds = null;

	private String[] localeIds;

	private String localeMapJavascript;
	
	private String newDefaultAcctNum;
	
	private String submitType;
	
	private String vendorState;
	
	private String phone2;
	
	private String vendorCountry;
	
	private String fax;
	
	private String accountNumber;
	
	private String title;
	
	private String vendorType;
	
	private Float discountPercentage;
	
	private int discountIfInDays;
	
	private int discountDueInDays;
	
	private String vendor1099Type;
	
	private Float vendor1099Payment;
	
	private String taxID;
	
	private String approvedVendor;
	
	private Float creditLimit;
	
	private long apAccountID;	
	
	private ArrayList <LabelValueBean> type1099Values = new ArrayList <LabelValueBean> ();	
	
	private String direction;
	
	private String def_localeID;
	private String def_locationID;
	
	private String vendorCodeLength;
	
	public String getVendorCodeLength() {
		return vendorCodeLength;
	}

	public void setVendorCodeLength(String vendorCodeLength) {
		this.vendorCodeLength = vendorCodeLength;
	}

	public String getDef_localeID() {
		return def_localeID;
	}

	public void setDef_localeID(String def_localeID) {
		this.def_localeID = def_localeID;
	}

	public String getDef_locationID() {
		return def_locationID;
	}

	public void setDef_locationID(String def_locationID) {
		this.def_locationID = def_locationID;
	}

	/**
	 * @return the directive
	 */
	public String getDirection() {
		return direction;
	}

	/**
	 * @param directive the directive to set
	 */
	public void setDirection(String direction) {
		this.direction = direction;
	}

	/**
	 * @return the addr1
	 */
	public String getAddr1() {
		return addr1;
	}

	/**
	 * @return the addr2
	 */
	public String getAddr2() {
		return addr2;
	}

	/**
	 * @return the cityState
	 */
	public String getCityState() {
		return cityState;
	}
	
	/**
	 * @return the contactName
	 */
	public String getContactName() {
		return contactName;
	}

	/**
	 * @return the defaultAcct
	 */
	public String getDefaultAcct() {
		return defaultAcct;
	}

	/**
	 * @return the deleteCode
	 */
	public String getDeleteCode() {
		return deleteCode;
	}

	/**
	 * @return the emailAddr
	 */
	public String getEmailAddr() {
		return emailAddr;
	}

	/**
	 * @return the localeID
	 */
	public long getLocaleID() {
		return localeID;
	}

	/**
	 * @return the locationID
	 */
	public long getLocationID() {
		return locationID;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @return the notes
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * @return the phone
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * @return the postalCode
	 */
	public String getPostalCode() {
		return postalCode;
	}

	/**
	 * @return the vendorID
	 */
	public long getVendorID() {
		return vendorID;
	}

	/**
	 * @param addr1 the addr1 to set
	 */
	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	/**
	 * @param addr2 the addr2 to set
	 */
	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	/**
	 * @param cityState the cityState to set
	 */
	public void setCityState(String cityState) {
		this.cityState = cityState;
	}
	
	
	/**
	 * @param contactName the contactName to set
	 */
	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	/**
	 * @param defaultAcct the defaultAcct to set
	 */
	public void setDefaultAcct(String defaultAcct) {
		this.defaultAcct = defaultAcct;
	}

	/**
	 * @param deleteCode the deleteCode to set
	 */
	public void setDeleteCode(String deleteCode) {
		this.deleteCode = deleteCode;
	}

	/**
	 * @param emailAddr the emailAddr to set
	 */
	public void setEmailAddr(String emailAddr) {
		this.emailAddr = emailAddr;
	}

	/**
	 * @param localeID the localeID to set
	 */
	public void setLocaleID(long localeID) {
		this.localeID = localeID;
	}

	/**
	 * @param locationID the locationID to set
	 */
	public void setLocationID(long locationID) {
		this.locationID = locationID;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @param notes the notes to set
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * @param phone the phone to set
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * @param postalCode the postalCode to set
	 */
	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	/**
	 * @param vendorID the vendorID to set
	 */
	public void setVendorID(long vendorID) {
		this.vendorID = vendorID;
	}
	
	/**
	 * @return the internalVendor
	 */
	public String getInternalVendor() {
		return internalVendor;
	}

	/**
	 * @param internalVendor the internalVendor to set
	 */
	public void setInternalVendor(String internalVendor) {
		this.internalVendor = internalVendor;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		//return super.validate(actionMapping, request);
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * @return the localeIds
	 */
	public String[] getLocaleIds() {
		return localeIds;
	}

	/**
	 * @return the localeMapJavascript
	 */
	public String getLocaleMapJavascript() {
		return localeMapJavascript;
	}

	/**
	 * @return the locationIds
	 */
	public String[] getLocationIds() {
		return locationIds;
	}

	/**
	 * @param localeIds the localeIds to set
	 */
	public void setLocaleIds(String[] localeIds) {
		this.localeIds = localeIds;
	}

	/**
	 * @param localeMapJavascript the localeMapJavascript to set
	 */
	public void setLocaleMapJavascript(String localeMapJavascript) {
		this.localeMapJavascript = localeMapJavascript;
	}

	/**
	 * @param locationIds the locationIds to set
	 */
	public void setLocationIds(String[] locationIds) {
		this.locationIds = locationIds;
	}

	/**
	 * @return the newDefaultAcctNum
	 */
	public String getNewDefaultAcctNum() {
		return newDefaultAcctNum;
	}

	/**
	 * @param newDefaultAcctNum the newDefaultAcctNum to set
	 */
	public void setNewDefaultAcctNum(String newDefaultAcctNum) {
		this.newDefaultAcctNum = newDefaultAcctNum;
	}

	/**
	 * @return the submitType
	 */
	public String getSubmitType() {
		return submitType;
	}

	/**
	 * @param submitType the submitType to set
	 */
	public void setSubmitType(String submitType) {
		this.submitType = submitType;
	}
	
	/**
	 * @return the vendorState
	 */
	public String getVendorState() {
		return vendorState;
	}

	/**
	 * @param state the state to set
	 */
	public void setVendorState(String vendorState) {
		this.vendorState = vendorState;
	}	
	/**
	 * @return the phone2
	 */
	public String getPhone2() {
		return phone2;
	}

	/**
	 * @param phone2 the phone2 to set
	 */
	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}	
	/**
	 * @return the country
	 */
	public String getVendorCountry() {
		return vendorCountry;
	}
	/**
	 * @param country the country to set
	 */
	public void setVendorCountry(String vendorCountry) {
		this.vendorCountry = vendorCountry;
	}			
	/**
	 * @return the fax
	 */
	public String getFax() {
		return fax;
	}	
	/**
	 * @param fax the fax to set
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}
	/**
	 * @return the accountNumber
	 */
	public String getAccountNumber() {
		return accountNumber;
	}	
	/**
	 * @param accountNumber the accountNumber to set
	 */
	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}				
	/**
	 * @return the Title
	 */
	public String getTitle() {
		return title;
	}	
	/**
	 * @param Title the Title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}				
	/**
	 * @return the VendorType
	 */
	public String getVendorType() {
		return vendorType;
	}	
	/**
	 * @param VendorType the VendorType to set
	 */
	public void setVendorType(String vendorType) {
		this.vendorType = vendorType;
	}				
	/**
	 * @return the DiscountPercentage
	 */
	public Float getDiscountPercentage() {
		return discountPercentage;
	}	
	/**
	 * @param discountPercentage the discountPercentage to set
	 */
	public void setDiscountPercentage(Float discountPercentage) {
		this.discountPercentage = discountPercentage;
	}		
	/**
	 * @return the DiscountIfInDays
	 */
	public int getDiscountIfInDays() {
		return discountIfInDays;
	}	
	/**
	 * @param discountIfInDays the discountIfInDays to set
	 */
	public void setDiscountIfInDays(int discountIfInDays) {
		this.discountIfInDays = discountIfInDays;
	}			
	/**
	 * @return the DiscountDueInDays
	 */
	public int getDiscountDueInDays() {
		return discountDueInDays;
	}	
	/**
	 * @param discountDueInDays the discountDueInDays to set
	 */
	public void setDiscountDueInDays(int discountDueInDays) {
		this.discountDueInDays = discountDueInDays;
	}				
	/**
	 * @return the vendor1099Type
	 */
	public String getVendor1099Type() {
		return vendor1099Type;
	}	
	/**
	 * @param vendor1099Type the vendor1099Type to set
	 */
	public void setVendor1099Type(String vendor1099Type) {
		this.vendor1099Type = vendor1099Type;
	}				
	/**
	 * @return the vendor1099Payment
	 */
	public Float getVendor1099Payment() {
		return vendor1099Payment;
	}	
	/**
	 * @param vendor1099Payment the vendor1099Payment to set
	 */
	public void setVendor1099Payment(Float vendor1099Payment) {
		this.vendor1099Payment = vendor1099Payment;
	}					
	/**
	 * @return the TaxID
	 */
	public String getTaxID() {
		return taxID;
	}	
	/**
	 * @param TaxID the TaxID to set
	 */
	public void setTaxID(String taxID) {
		this.taxID = taxID;
	}			
	/**
	 * @return the ApprovedVendor
	 */
	public String getApprovedVendor() {
		return approvedVendor;
	}	
	/**
	 * @param ApprovedVendor the ApprovedVendor to set
	 */
	public void setApprovedVendor(String approvedVendor) {
		this.approvedVendor = approvedVendor;
	}			
	/**
	 * @return the CreditLimit
	 */
	public Float getCreditLimit() {
		return creditLimit;
	}	
	/**
	 * @param CreditLimit the CreditLimit to set
	 */
	public void setCreditLimit(Float creditLimit) {
		this.creditLimit = creditLimit;
	}

	/**
	 * @return the type1099Values
	 */
	public ArrayList<LabelValueBean> getType1099Values() {
		return type1099Values;
	}

	/**
	 * @param type1099Values the type1099Values to set
	 */
	public void setType1099Values(ArrayList<LabelValueBean> type1099Values) {
		this.type1099Values = type1099Values;
	}

	/**
	 * @return the apAccountID
	 */
	public long getApAccountID() {
		return apAccountID;
	}

	/**
	 * @param apAccountID the apAccountID to set
	 */
	public void setApAccountID(long apAccountID) {
		this.apAccountID = apAccountID;
	}

	/**
	 * @return the vendorCode
	 */
	public String getVendorCode() {
		return vendorCode;
	}

	/**
	 * @param vendorCode the vendorCode to set
	 */
	public void setVendorCode(String vendorCode) {
		this.vendorCode = vendorCode;
	}	
	
	
}