CREATE TABLE AUDIT_LOG (
	AUDIT_ID		INT(11) NOT NULL AUTO_INCREMENT,
	COMPANY_ID		INT(11) NOT NULL,
	LOCALE_ID		INT(11) NOT NULL,
	USER_ID			INT(11) NOT NULL,
	MESSAGE			TEXT,
	CREATED_DATE	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (AUDIT_ID)
);